 ********************************************************************************************;
 ** SAS Program: 06b_aggregation_var2_new.sas                                              **;
 ** Description: Attribute Aggregation for second set of NC+ attributes.  Aggregation code **;
 **              for Keystone Attributes to be used in final financial score development.  **;
 **              November NC+ Extract for NC+ Financial Score - Account Acquisition.       **;
 **     Updated: 07/08/2011                                                                **;
 ********************************************************************************************;
/* shewjen - using all_temp instead of all so we do not have to create a duplicate dataset */
 
proc sort data=all_temp out=xy0; /* shewjen - all to all_temp */
by cnxid descending mos_since_reported;
run;

Data xy0;
set xy0;
by cnxid;

if (first.cnxid) then do;
 num_accounts_rep_6=0;
end;

  *** TOT0104   -       Number of Accounts Reported in Last 6 Months ***;
  if cnxid=' ' then num_accounts_rep_6=99;
  else if cnxid ne ' ' and (mos_since_reported > 5) then num_accounts_rep_6=97;
  else if (cnxid ne ' ' and 0 <= mos_since_reported <=5) then do;
     if num_accounts_rep_6=97 then num_accounts_rep_6=0;
     if num_accounts_rep_6=94 then num_accounts_rep_6=0;
     if num_accounts_rep_6 <= 92 then num_accounts_rep_6+1;
  end;

run;

proc sort data=all_temp out=all1;  /* shewjen - all to all_temp */
by cnxid descending mos_since_connected;
run;

Data xy1;
set all1;
by cnxid;

if (first.cnxid) then do;
   n=0;
   n_disconnect=0;
   n_inv_disconnect=0;
   n_vol_disconnect=0;
end;

n+1;

if (mos_since_disconnected < 999) then n_disconnect+1;

******* Avg Age of Involuntary Disconnection ********;
if last_status in ('B','N','P','U') and (mos_since_disconnected <= 92) then n_inv_disconnect+1;

******* Avg Age of Voluntary Disconnection ********;
if last_status not in (' ','B','N','P','U') and (mos_since_disconnected <= 92) then n_vol_disconnect+1;

 *** TOT0201 - Number of Months Since the Oldest Connection ***;

 *** TOT0203 - Number of Months since Most Recent Connection ***;

 if cnxid=' ' then age_connected2=999;
 else if cnxid ne ' ' and mos_since_connected=999 then age_connected2=995;
 else if cnxid ne ' ' and (0 <= mos_since_connected <= 992) then do;
    if age_connected2=995 then age_connected2=0;
    if age_connected2 <= 992 then age_connected2=mos_since_connected;
 end;

keep cnxid last_status Disconnect_dt n n_disconnect n_inv_disconnect n_vol_disconnect mos_since_connected mos_since_disconnected mos_since_reported age_connected2;

run;

proc sort data=xy1(keep=cnxid n n_disconnect n_inv_disconnect n_vol_disconnect mos_since_connected) out=titon;
by cnxid;
run;

proc sort data=all_temp out=all2;  /* shewjen - all to all_temp */
by cnxid descending last_status descending mos_since_connected;
run;

Data xy2;
set all2;
by cnxid;

 *** TOT0202 - Number of Months Since the Oldest Connection Satisfactory Accounts ***;

if cnxid=' ' then age_0_connected2=999;
else if cnxid ne ' ' and last_status ne '0' then age_0_connected2=995;
else if cnxid ne ' ' and last_status = '0' and mos_since_connected=999 then age_0_connected2=995;
else if cnxid ne ' ' and last_status = '0' and (0 <= mos_since_connected <= 992) then do;
   if age_0_connected2=995 then age_0_connected2=0;
   age_0_connected2=mos_since_connected;
end;

 *** TOT0204 - Number of Months since Most Recent Connection Satisfactory Accounts ***;

if cnxid=' ' then age_0_connected2_6=999;
else if cnxid ne ' ' and last_status_6 ne '0' then age_0_connected2_6=995;
else if cnxid ne ' ' and last_status_6 = '0' and mos_since_connected=999 then age_0_connected2_6=995;
else if cnxid ne ' ' and last_status_6 = '0' and (0 <= mos_since_connected <= 992) then do;
   if age_0_connected2_6=995 then age_0_connected2_6=0;
   age_0_connected2_6=mos_since_connected;
end;

keep cnxid last_status last_status_6 mos_since_connected age_0_connected2 age_0_connected2_6;

run;

proc sort data=all_temp out=all3;  /* shewjen - all to all_temp */
by cnxid descending mos_since_disconnected;
run;

Data xy3;
set all3;
by cnxid;

 *** TOT0205 - Number of Months since Most Recent Disconnection ***;

 if cnxid=' ' then age_disconnected2=999;
 else if cnxid ne ' ' and mos_since_disconnected=999 then age_disconnected2=995;
 else if cnxid ne ' ' and (0 <= mos_since_disconnected <= 992) then do;
    if age_disconnected2=995 then age_disconnected2=0;
    if age_disconnected2 <= 992 then age_disconnected2=mos_since_disconnected;
 end;

keep cnxid mos_since_disconnected age_disconnected2;

run;

proc sort data=all_temp out=all4;  /* shewjen - all to all_temp */
by cnxid descending last_status descending mos_since_disconnected;
run;

Data xy4;
set all4;
by cnxid;

 *** TOT0206 - Number of Months since Most Recent Involuntary Disconnection ***;

 if cnxid=' ' then age_inv_disconnected2=999; 
 else if cnxid ne ' ' and (last_status not in ('B','N','P','U') ) then age_inv_disconnected2=995;
 else if cnxid ne ' ' and (last_status in ('B','N','P','U') ) and mos_since_disconnected=999 then do;
   age_inv_disconnected2=995;
 end;
 else if cnxid ne ' ' and (0 <= mos_since_disconnected <= 992) and (last_status in ('B','N','P','U') ) then do;
    if age_inv_disconnected2=995 then age_inv_disconnected2=0;
    if age_inv_disconnected2 <= 992 then age_inv_disconnected2=mos_since_disconnected;
 end;
 
 
 *** TOT0207 - Number of Months since Most Recent Voluntary Disconnection ***;

 if cnxid=' ' then age_vol_disconnected2=999;
 else if cnxid ne ' ' and (last_status in (' ','B','N','P','U') ) then age_vol_disconnected2=995;
 else if cnxid ne ' ' and (last_status not in (' ','B','N','P','U') ) and mos_since_disconnected=999 then do;
   age_vol_disconnected2=995;
 end;
 else if cnxid ne ' ' and (0 <= mos_since_disconnected <= 992) and (last_status not in (' ','B','N','P','U') ) then do;
    if age_vol_disconnected2=995 then age_vol_disconnected2=0;
    if age_vol_disconnected2 <= 992 then age_vol_disconnected2=mos_since_disconnected;
 end;

keep cnxid last_status mos_since_disconnected last_status age_inv_disconnected2 age_vol_disconnected2;

run;

proc sort data=all_temp out=all5;   /* shewjen - all to all_temp */
by cnxid descending mos_since_reported;
run;

Data xy5;
set all5;
by cnxid;

if (first.cnxid) then do;
 num_0_wrst=0;
 num_0_wrst_3=0;
 num_0_wrst_6=0;
 num_0_wrst_12=0;
 num_1_wrst=0;
 num_1_wrst_3=0;
 num_1_wrst_6=0;
 num_1_wrst_12=0;
 num_2_wrst_3=0;
 num_2_wrst_6=0;
 num_2_wrst_12=0;
 num_2p_wrst=0;
 num_2p_wrst_3=0;
 num_2p_wrst_6=0;
 num_2p_wrst_12=0;
 num_2p_unpaid_wrst=0;

 num_2p_unpaid_wrst_3=0;
 num_2p_unpaid_wrst_6=0;
 num_2p_unpaid_wrst_12=0;
 num_3p_wrst=0;
 num_3p_wrst_3=0;
 num_3p_wrst_6=0;
 num_3p_wrst_12=0;
 num_3p_unpaid_wrst=0;
 num_3p_unpaid_wrst_3=0;
 num_3p_unpaid_wrst_6=0;
 num_3p_unpaid_wrst_12=0;

%macro r(q);

temp_0_num_&q._3=0;
temp_1_num_&q._3=0;
temp_2_num_&q._3=0;

temp_0_num_&q._6=0;
temp_1_num_&q._6=0;
temp_2_num_&q._6=0;
temp_3_num_&q._6=0;
temp_4_num_&q._6=0;
temp_5_num_&q._6=0;

temp_0_num_&q._12=0;
temp_1_num_&q._12=0;
temp_2_num_&q._12=0;
temp_3_num_&q._12=0;
temp_4_num_&q._12=0;
temp_5_num_&q._12=0;
temp_6_num_&q._12=0;
temp_7_num_&q._12=0;
temp_8_num_&q._12=0;
temp_9_num_&q._12=0;
temp_10_num_&q._12=0;
temp_11_num_&q._12=0;

%mend;
%r(0);
%r(1);
%r(2);

end;

 *** New Current worst rating - last rep within 6 months (wrst=worst_new) ****;
 ***    TOT0301 -       Worst Current Rating ***;

 length grid_6 $6.;

 grid_6=Acct_status||S01||S02||S03||S04||S05;

if cnxid=' ' then wrst=99;
else if cnxid ne ' ' and ( mos_since_reported > 5) then wrst=97;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and compress(grid_6)=' ' then do;
   if wrst=97 then wrst=95;
   else wrst=95;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and compress(grid_6) ne ' ' then do;
 if wrst=97 then wrst=0;
 if wrst=95 then wrst=0;

 if (0 <= mos_since_reported <= 5) &
    (substr(grid_6,1,1) in ('B','N','U','P') ) then wrst=6;
 else if (0 <= mos_since_reported <= 5) &
      (substr(grid_6,1,1) in ('3','4','5','6') ) then wrst=5;
 else if (0 <= mos_since_reported <= 5) &
      (substr(grid_6,1,1) in ('2') ) then wrst=4;
 else if (0 <= mos_since_reported <= 5) &
      (substr(grid_6,1,1) in ('1') ) then wrst=3;
 else if (0 <= mos_since_reported <= 5) &
      (substr(grid_6,1,1) in ('0') ) then wrst=2;
 else if (0 <= mos_since_reported <= 5) &
      (substr(grid_6,1,1) in ('9') ) then wrst=1;

 if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
    (substr(grid_6,2,1) in ('B','N','U','P') ) then wrst=6;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      (substr(grid_6,2,1) in ('3','4','5','6') ) then wrst=5;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      (substr(grid_6,2,1) in ('2') ) then wrst=4;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      (substr(grid_6,2,1) in ('1') ) then wrst=3;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      (substr(grid_6,2,1) in ('0') ) then wrst=2;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      (substr(grid_6,2,1) in ('9') ) then wrst=1;

 if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
    ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
    (substr(grid_6,3,1) in ('B','N','U','P') ) then wrst=6;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      (substr(grid_6,3,1) in ('3','4','5','6') ) then wrst=5;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      (substr(grid_6,3,1) in ('2') ) then wrst=4;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      (substr(grid_6,3,1) in ('1') ) then wrst=3;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      (substr(grid_6,3,1) in ('0') ) then wrst=2;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      (substr(grid_6,3,1) in ('9') ) then wrst=1;

  if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
    ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
    ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
    (substr(grid_6,4,1) in ('B','N','U','P') ) then wrst=6;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      (substr(grid_6,4,1) in ('3','4','5','6') ) then wrst=5;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      (substr(grid_6,4,1) in ('2') ) then wrst=4;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      (substr(grid_6,4,1) in ('1') ) then wrst=3;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      (substr(grid_6,4,1) in ('0') ) then wrst=2;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      (substr(grid_6,4,1) in ('9') ) then wrst=1;

 if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
    ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
    ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
    ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
    (substr(grid_6,5,1) in ('B','N','U','P') ) then wrst=6;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      (substr(grid_6,5,1) in ('3','4','5','6') ) then wrst=5;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      (substr(grid_6,5,1) in ('2') ) then wrst=4;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      (substr(grid_6,5,1) in ('1') ) then wrst=3;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      (substr(grid_6,5,1) in ('0') ) then wrst=2;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      (substr(grid_6,5,1) in ('9') ) then wrst=1;

  if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
    ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
    ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
    ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
    ( (substr(grid_6,5,1) in ('D','X') )|(substr(grid_6,5,1)=' ') ) &
    (substr(grid_6,6,1) in ('B','N','U','P') ) then wrst=6;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      ( (substr(grid_6,5,1) in ('D','X') )|(substr(grid_6,5,1)=' ') ) &
      (substr(grid_6,6,1) in ('3','4','5','6') ) then wrst=5;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      ( (substr(grid_6,5,1) in ('D','X') )|(substr(grid_6,5,1)=' ') ) &
      (substr(grid_6,6,1) in ('2') ) then wrst=4;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      ( (substr(grid_6,5,1) in ('D','X') )|(substr(grid_6,5,1)=' ') ) &
      (substr(grid_6,6,1) in ('1') ) then wrst=3;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      ( (substr(grid_6,5,1) in ('D','X') )|(substr(grid_6,5,1)=' ') ) &
      (substr(grid_6,6,1) in ('0') ) then wrst=2;
 else if (0 <= mos_since_reported <= 5) & ( (substr(grid_6,1,1) in ('D','X') )|(substr(grid_6,1,1)=' ') ) &
      ( (substr(grid_6,2,1) in ('D','X') )|(substr(grid_6,2,1)=' ') ) &
      ( (substr(grid_6,3,1) in ('D','X') )|(substr(grid_6,3,1)=' ') ) &
      ( (substr(grid_6,4,1) in ('D','X') )|(substr(grid_6,4,1)=' ') ) &
      ( (substr(grid_6,5,1) in ('D','X') )|(substr(grid_6,5,1)=' ') ) &
      (substr(grid_6,6,1) in ('9') ) then wrst=1;

end;

***     TOT0304 -       Worst Rating in Last 12 Months ***;

length grid_12 $12.;

grid_12=Acct_status||s01||s02||s03||s04||s05||s06||s07||s08||s09||s10||s11;

if cnxid=' ' then wrst_12=99;
else if cnxid ne ' ' and ( mos_since_reported > 11) then wrst_12=97;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and compress(grid_12)=' ' then do;
   if wrst_12=97 then wrst_12=95;
   else wrst_12=95;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and compress(grid_12) ne ' ' then do;
   if wrst_12=97 then wrst_12=0;
   if wrst_12=95 then wrst_12=0;

if (0 <= mos_since_reported <= 11) &
   (
   (Acct_status in ('B','N','U','P') ) |
   (s01 in ('B','N','U','P') ) |
   (s02 in ('B','N','U','P') ) |
   (s03 in ('B','N','U','P') ) |
   (s04 in ('B','N','U','P') ) |
   (s05 in ('B','N','U','P') ) |
   (s06 in ('B','N','U','P') ) |
   (s07 in ('B','N','U','P') ) |
   (s08 in ('B','N','U','P') ) |
   (s09 in ('B','N','U','P') ) |
   (s10 in ('B','N','U','P') ) |
   (s11 in ('B','N','U','P') )
   )
   then wrst_12=6;
else if (0 <= mos_since_reported <= 11) &
     (
   (Acct_status in ('3','4','5','6')) |
   (s01 in ('3','4','5','6')) |
   (s02 in ('3','4','5','6')) |
   (s03 in ('3','4','5','6')) |
   (s04 in ('3','4','5','6')) |
   (s05 in ('3','4','5','6')) |
   (s06 in ('3','4','5','6')) |
   (s07 in ('3','4','5','6')) |
   (s08 in ('3','4','5','6')) |
   (s09 in ('3','4','5','6')) |
   (s10 in ('3','4','5','6')) |
   (s11 in ('3','4','5','6'))
   )
   then wrst_12=5;
else if (0 <= mos_since_reported <= 11) &
   (
   (Acct_status in ('2')) |
   (s01 in ('2')) |
   (s02 in ('2')) |
   (s03 in ('2')) |
   (s04 in ('2')) |
   (s05 in ('2')) |
   (s06 in ('2')) |
   (s07 in ('2')) |
   (s08 in ('2')) |
   (s09 in ('2')) |
   (s10 in ('2')) |
   (s11 in ('2'))
   )
   then wrst_12=4;
else if (0 <= mos_since_reported <= 11) &
     (
   (Acct_status in ('1')) |
   (s01 in ('1')) |
   (s02 in ('1')) |
   (s03 in ('1')) |
   (s04 in ('1')) |
   (s05 in ('1')) |
   (s06 in ('1')) |
   (s07 in ('1')) |
   (s08 in ('1')) |
   (s09 in ('1')) |
   (s10 in ('1')) |
   (s11 in ('1'))
   )
   then wrst_12=3;
else if (0 <= mos_since_reported <= 11) &
   (
   (Acct_status in ('0')) |
   (s01 in ('0')) |
   (s02 in ('0')) |
   (s03 in ('0')) |
   (s04 in ('0')) |
   (s05 in ('0')) |
   (s06 in ('0')) |
   (s07 in ('0')) |
   (s08 in ('0')) |
   (s09 in ('0')) |
   (s10 in ('0')) |
   (s11 in ('0'))
   )
   then wrst_12=2;
else if (0 <= mos_since_reported <= 11) &
    (
   (Acct_status in ('9')) |
   (s01 in ('9')) |
   (s02 in ('9')) |
   (s03 in ('9')) |
   (s04 in ('9')) |
   (s05 in ('9')) |
   (s06 in ('9')) |
   (s07 in ('9')) |
   (s08 in ('9')) |
   (s09 in ('9')) |
   (s10 in ('9')) |
   (s11 in ('9'))
   )
   then wrst_12=1;
end;

***     TOT0303 -       Worst Rating in Last 6 Months ***;

length grid_6 $6.;

grid_6=Acct_status||s01||s02||s03||s04||s05;

if cnxid=' ' then wrst_6=99;
else if cnxid ne ' ' and ( mos_since_reported > 5) then wrst_6=97;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and compress(grid_6)=' ' then do;
   if wrst_6=97 then wrst_6=95;
   else wrst_6=95;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and compress(grid_6) ne ' ' then do;
   if wrst_6=97 then wrst_6=0;
   if wrst_6=95 then wrst_6=0;

if (0 <= mos_since_reported <= 5) &
   (
   (Acct_status in ('B','N','U','P') ) |
   (s01 in ('B','N','U','P') ) |
   (s02 in ('B','N','U','P') ) |
   (s03 in ('B','N','U','P') ) |
   (s04 in ('B','N','U','P') ) |
   (s05 in ('B','N','U','P') )
   )
   then wrst_6=6;
else if (0 <= mos_since_reported <= 5) &
     (
   (Acct_status in ('3','4','5','6')) |
   (s01 in ('3','4','5','6')) |
   (s02 in ('3','4','5','6')) |
   (s03 in ('3','4','5','6')) |
   (s04 in ('3','4','5','6')) |
   (s05 in ('3','4','5','6'))
   )
   then wrst_6=5;
else if (0 <= mos_since_reported <= 5) &
   (
   (Acct_status in ('2')) |
   (s01 in ('2')) |
   (s02 in ('2')) |
   (s03 in ('2')) |
   (s04 in ('2')) |
   (s05 in ('2'))
   )
   then wrst_6=4;
else if (0 <= mos_since_reported <= 5) &
     (
   (Acct_status in ('1')) |
   (s01 in ('1')) |
   (s02 in ('1')) |
   (s03 in ('1')) |
   (s04 in ('1')) |
   (s05 in ('1'))
   )
   then wrst_6=3;
else if (0 <= mos_since_reported <= 5) &
   (
   (Acct_status in ('0')) |
   (s01 in ('0')) |
   (s02 in ('0')) |
   (s03 in ('0')) |
   (s04 in ('0')) |
   (s05 in ('0'))
   )
   then wrst_6=2;
else if (0 <= mos_since_reported <= 5) &
    (
   (Acct_status in ('9')) |
   (s01 in ('9')) |
   (s02 in ('9')) |
   (s03 in ('9')) |
   (s04 in ('9')) |
   (s05 in ('9'))
   )
   then wrst_6=1;

end;

***     TOT0302 -       Worst Rating in Last 3 Months ***;

length grid_3 $3.;

grid_3=Acct_status||s01||s02;

if cnxid=' ' then wrst_3=99;
else if cnxid ne ' ' and ( mos_since_reported > 2) then wrst_3=97;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and grid_3=' ' then do;
   if wrst_3=97 then wrst_3=95;
   else wrst_3=95;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and grid_3 ne ' ' then do;
   if wrst_3=97 then wrst_3=0;
   if wrst_3=95 then wrst_3=0;

if (0 <= mos_since_reported <= 2) &
   (
   (Acct_status in ('B','N','U','P') ) |
   (s01 in ('B','N','U','P') ) |
   (s02 in ('B','N','U','P') )
   )
   then wrst_3=6;
else if (0 <= mos_since_reported <= 2) &
     (
   (Acct_status in ('3','4','5','6')) |
   (s01 in ('3','4','5','6')) |
   (s02 in ('3','4','5','6'))
   )
   then wrst_3=5;
else if (0 <= mos_since_reported <= 2) &
    (
    (Acct_status in ('2')) |
   (s01 in ('2')) |
   (s02 in ('2'))
   )
   then wrst_3=4;
else if (0 <= mos_since_reported <= 2) &
     (
   (Acct_status in ('1')) |
   (s01 in ('1')) |
   (s02 in ('1'))
   )
   then wrst_3=3;
else if (0 <= mos_since_reported <= 2) &
   (
   (Acct_status in ('0')) |
   (s01 in ('0')) |
   (s02 in ('0'))
   )
   then wrst_3=2;
else if (0 <= mos_since_reported <= 2) &
     (
   (Acct_status in ('9')) |
   (s01 in ('9')) |
   (s02 in ('9'))
   )
   then wrst_3=1;

end;

 ***    TOT0116 -       Number of Worst Rating Satisfactory Accounts ***;
 ***    TOT0117 -       Number of Worst Rating Satisfactory Accounts in Last 3 Months ***;
 ***    TOT0118 -       Number of Worst Rating Satisfactory Accounts in Last 6 Months ***;
 ***    TOT0119 -       Number of Worst Rating Satisfactory Accounts in Last 12 Months ***;
 ***    TOT0120 -       Number of Worst Rating 30 dpd Accounts ***;
 ***    TOT0121 -       Number of Worst Rating 30 dpd Accounts in Last 3 Months ***;
 ***    TOT0122 -       Number of Worst Rating 30 dpd Accounts in Last 6 Months ***;
 ***    TOT0123 -       Number of Worst Rating 30 dpd Accounts in Last 12 Months ***;
 ***    TOT0124 -       Number of Worst Rating 60+ dpd Accounts ***;
 ***    TOT0125 -       Number of Worst Rating 60+ dpd Accounts in Last 3 Months ***;
 ***    TOT0126 -       Number of Worst Rating 60+ dpd Accounts in Last 6 Months ***;
 ***    TOT0127 -       Number of Worst Rating 60+ dpd Accounts in Last 12 Months ***;
 ***    TOT0128 -       Number of Worst Rating 60+ dpd or Unpaid Closed Accounts ***;
 ***    TOT0129 -       Number of Worst Rating 60+ dpd or Unpaid Closed Accounts in Last 3 Months ***;
 ***    TOT0130 -       Number of Worst Rating 60+ dpd or Unpaid Closed Accounts in Last 6 Months ***;
 ***    TOT0131 -       Number of Worst Rating 60+ dpd or Unpaid Closed Accounts in Last 12 Months ***;
 ***    TOT0132 -       Number of Worst Rating 90+ dpd Accounts ***;
 ***    TOT0133 -       Number of Worst Rating 90+ dpd Accounts in Last 3 Months ***;
 ***    TOT0134 -       Number of Worst Rating 90+ dpd Accounts in Last 6 Months ***;
 ***    TOT0135 -       Number of Worst Rating 90+ dpd Accounts in Last 12 Months ***;
 ***    TOT0136 -       Number of Worst Rating 90+ dpd or Unpaid Closed Accounts ***;
 ***    TOT0137 -       Number of Worst Rating 90+ dpd or Unpaid Closed Accounts in Last 3 Months ***;
 ***    TOT0138 -       Number of Worst Rating 90+ dpd or Unpaid Closed Accounts in Last 6 Months ***;
 ***    TOT0139 -       Number of Worst Rating 90+ dpd or Unpaid Closed Accounts in Last 12 Months ***;

%macro cwrst(wrstvar,mos);

if cnxid=' ' then do;
   num_0_&wrstvar=99;
   num_1_&wrstvar=99;
   num_2_&wrstvar=99;
   num_2p_&wrstvar=99;
   num_2p_unpaid_&wrstvar=99;
   num_3p_&wrstvar=99;
   num_3p_unpaid_&wrstvar=99;
end;
if cnxid ne ' ' and &wrstvar=97 then do;
      num_0_&wrstvar=97;
      num_1_&wrstvar=97;
      num_2_&wrstvar=97;
      num_2p_&wrstvar=97;
      num_2p_unpaid_&wrstvar=97;
      num_3p_&wrstvar=97;
      num_3p_unpaid_&wrstvar=97;
   end;
else if cnxid ne ' ' and &wrstvar=95 then do;
   if num_0_&wrstvar=97 then num_0_&wrstvar=95;
   else num_0_&wrstvar=95;
   if num_1_&wrstvar=97 then num_1_&wrstvar=95;
   else num_1_&wrstvar=95;
   if num_2_&wrstvar=97 then num_2_&wrstvar=95;
   else num_2_&wrstvar=95;
   if num_2p_&wrstvar=97 then num_2p_&wrstvar=95;
   else num_2p_&wrstvar=95;
   if num_2p_unpaid_&wrstvar=97 then num_2p_unpaid_&wrstvar=95;
   else num_2p_unpaid_&wrstvar=95;
   if num_3p_&wrstvar=97 then num_3p_&wrstvar=95;
   else num_3p_&wrstvar=95;
   if num_3p_unpaid_&wrstvar=97 then num_3p_unpaid_&wrstvar=95;
   else num_3p_unpaid_&wrstvar=95;
end;

else if cnxid ne ' ' and (&wrstvar in (1,2,3,4,5,6) ) then do;

******** number of worst rating satisfactory accounts in last rep month,3,6,12 months ********;

  if num_0_&wrstvar=97 then num_0_&wrstvar=0;
  if num_0_&wrstvar=95 then num_0_&wrstvar=0;
  if (&wrstvar=2) then do;
     if num_0_&wrstvar <= 92 then num_0_&wrstvar+1;
  end;

******** number of worst rating 30 dpd accounts in last rep month,3,6,12 months ********;

  if num_1_&wrstvar=97 then num_1_&wrstvar=0;
  if num_1_&wrstvar=95 then num_1_&wrstvar=0;
  if (&wrstvar=3) then do;
     if num_1_&wrstvar <= 92 then num_1_&wrstvar+1;
  end;

******** number of worst rating 60 dpd accounts in last rep month,3,6,12 months *********;

  if num_2_&wrstvar=97 then num_2_&wrstvar=0;
  if num_2_&wrstvar=95 then num_2_&wrstvar=0;
  if (&wrstvar=4) then do;
     if num_2_&wrstvar <= 92 then num_2_&wrstvar+1;
  end;

******** number of worst rating 60 plus dpd accounts in last rep month,3,6,12 months ********;

  if num_2p_&wrstvar=97 then num_2p_&wrstvar=0;
  if num_2p_&wrstvar=95 then num_2p_&wrstvar=0;
  if (&wrstvar in (4,5)) then do;
     if num_2p_&wrstvar <= 92 then num_2p_&wrstvar+1;
  end;

******** number of worst rating 60 plus dpd or unpaid closed accounts in last rep month,3,6,12 months *********;

  if num_2p_unpaid_&wrstvar=97 then num_2p_unpaid_&wrstvar=0;
  if num_2p_unpaid_&wrstvar=95 then num_2p_unpaid_&wrstvar=0;
  if (&wrstvar in (4,5,6)) then do;
     if num_2p_unpaid_&wrstvar <= 92 then num_2p_unpaid_&wrstvar+1;
  end;

******** number of worst rating 90 plus dpd accounts in last rep month,3,6,12 months *********;
  if num_3p_&wrstvar=97 then num_3p_&wrstvar=0;
  if num_3p_&wrstvar=95 then num_3p_&wrstvar=0;
  if (&wrstvar=5) then do;
     if num_3p_&wrstvar <= 92 then num_3p_&wrstvar+1;
  end;

******** number of worst rating 90 plus dpd or unpaid closed accounts in last rep month,3,6,12 months *********;
  if num_3p_unpaid_&wrstvar=97 then num_3p_unpaid_&wrstvar=0;
  if num_3p_unpaid_&wrstvar=95 then num_3p_unpaid_&wrstvar=0;
  if (&wrstvar in (5,6)) then do;
     if num_3p_unpaid_&wrstvar <= 92 then num_3p_unpaid_&wrstvar+1;
  end;

end;

%mend;

%cwrst(wrst,5);
%cwrst(wrst_3,2);
%cwrst(wrst_6,5);
%cwrst(wrst_12,11);

*** Number Status(0,1,2) Occurrences in last 3 months ******;

%macro o3(m);

if cnxid=' ' then num_&m._3=99;
else if cnxid ne ' ' and (mos_since_reported > 2) then num_&m._3=97;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and (Acct_status ne "&m") and (s01 ne "&m") and (s02 ne "&m") then do;
   if num_&m._3=97 then num_&m._3=95;
   else num_&m._3=95;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and (Acct_status="&m"|s01="&m"|s02="&m") then do;

if (0 <= mos_since_reported <= 2) & Acct_status="&m" then do;
   temp_0_num_&m._3+1;
end;
if (0 <= mos_since_reported <= 2) & s01="&m" then do;
   temp_1_num_&m._3+1;
end;
if (0 <= mos_since_reported <= 2) & s02="&m" then do;
   temp_2_num_&m._3+1;
end;

if num_&m._3=97 then num_&m._3=0;
if num_&m._3=95 then num_&m._3=0;
if num_&m._3 <= 92 then do;
   num_&m._3=sum(temp_0_num_&m._3,temp_1_num_&m._3,temp_2_num_&m._3);
   if num_&m._3 > 92 then num_&m._3=92;
end;

end;

%mend;

%o3(0);
%o3(1);
%o3(2);

**** Number Status(0,1,2) Occurrences in last 6 months ******;
%macro o6(m);

if cnxid=' ' then num_&m._6=99;
else if cnxid ne ' ' and (mos_since_reported > 5) then num_&m._6=97;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and (Acct_status ne "&m") and (s01 ne "&m") and (s02 ne "&m") and (s03 ne "&m") and (s04 ne "&m") and (s05 ne "&m") then do;
   if num_&m._6=97 then num_&m._6=95;
   else num_&m._6=95;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and (Acct_status="&m"|s01="&m"|s02="&m"|s03="&m"|s04="&m"|s05="&m") then do;

if (0 <= mos_since_reported <= 5) & Acct_status="&m" then do;
   temp_0_num_&m._6+1;
end;
if (0 <= mos_since_reported <= 5) & s01="&m" then do;
   temp_1_num_&m._6+1;
end;
if (0 <= mos_since_reported <= 5) & s02="&m" then do;
   temp_2_num_&m._6+1;
end;
if (0 <= mos_since_reported <= 5) & s03="&m" then do;
   temp_3_num_&m._6+1;
end;
if (0 <= mos_since_reported <= 5) & s04="&m" then do;
   temp_4_num_&m._6+1;
end;
if (0 <= mos_since_reported <= 5) & s05="&m" then do;
   temp_5_num_&m._6+1;
end;

if num_&m._6=97 then num_&m._6=0;
if num_&m._6=95 then num_&m._6=0;
if num_&m._6 <= 92 then do;
   num_&m._6=sum(temp_0_num_&m._6,temp_1_num_&m._6,temp_2_num_&m._6,temp_3_num_&m._6,temp_4_num_&m._6,temp_5_num_&m._6);
   if num_&m._6 > 92 then num_&m._6=92;
end;

end;

%mend;

%o6(0);
%o6(1);
%o6(2);

**** Number Status(0,1,2) Occurrences in last 12 months ******;
%macro o12(m);

if cnxid=' ' then num_&m._12=99;
else if cnxid ne ' ' and (mos_since_reported > 11) then num_&m._12=97;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and (Acct_status ne "&m") and (s01 ne "&m") and (s02 ne "&m") and (s03 ne "&m") and (s04 ne "&m") and (s05 ne "&m") and
        (s06 ne "&m") and (s07 ne "&m") and (s08 ne "&m") and (s09 ne "&m") and (s10 ne "&m") and (s11 ne "&m") then do;
   if num_&m._12=97 then num_&m._12=95;
   else num_&m._12=95;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and (Acct_status="&m"|s01="&m"|s02="&m"|s03="&m"|s04="&m"|s05="&m"|s06="&m"|s07="&m"|s08="&m"|
                          s09="&m"|s10="&m"|s11="&m") then do;

if (0 <= mos_since_reported <= 11) & Acct_status="&m" then do;
   temp_0_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s01="&m" then do;
   temp_1_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s02="&m" then do;
   temp_2_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s03="&m" then do;
   temp_3_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s04="&m" then do;
   temp_4_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s05="&m" then do;
   temp_5_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s06="&m" then do;
   temp_6_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s07="&m" then do;
   temp_7_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s08="&m" then do;
   temp_8_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s09="&m" then do;
   temp_9_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s10="&m" then do;
   temp_10_num_&m._12+1;
end;
if (0 <= mos_since_reported <= 11) & s11="&m" then do;
   temp_11_num_&m._12+1;
end;

if num_&m._12=97 then num_&m._12=0;
if num_&m._12=95 then num_&m._12=0;
if num_&m._12 <= 92 then do;

   num_&m._12=sum(temp_0_num_&m._12,temp_1_num_&m._12,temp_2_num_&m._12,temp_3_num_&m._12,temp_4_num_&m._12,temp_5_num_&m._12,
            temp_6_num_&m._12,temp_7_num_&m._12,temp_8_num_&m._12,temp_9_num_&m._12,temp_10_num_&m._12,temp_11_num_&m._12);
   if num_&m._12 > 92 then num_&m._12=92;
end;

end;

%mend;

%o12(0);
%o12(1);
%o12(2);

keep cnxid mos_since_reported grid_3 grid_6 grid_12 Acct_status s01 s02 s03 s04 s05 s06 s07 s08 s09 s10 s11 wrst wrst_3 wrst_6 wrst_12
     S12 S13 S14 S15 S16 S17 S18 S19 S20 S21 S22 S23 S24
     num_0_wrst num_0_wrst_3 num_0_wrst_6 num_0_wrst_12
     num_1_wrst num_1_wrst_3 num_1_wrst_6 num_1_wrst_12
     num_2_wrst num_2_wrst_3 num_2_wrst_6 num_2_wrst_12
     num_2p_unpaid_wrst num_2p_unpaid_wrst_3 num_2p_unpaid_wrst_6 num_2p_unpaid_wrst_12
     num_2p_wrst num_2p_wrst_3 num_2p_wrst_6 num_2p_wrst_12
     num_3p_unpaid_wrst num_3p_unpaid_wrst_3 num_3p_unpaid_wrst_6 num_3p_unpaid_wrst_12
     num_3p_wrst num_3p_wrst_3 num_3p_wrst_6 num_3p_wrst_12
     num_0_3 num_1_3 num_2_3
     num_0_6 num_1_6 num_2_6
     num_0_12 num_1_12 num_2_12
;

run;

Data xy51;
set xy5;
if num_2p_wrst < 92;
run;

Data xy6;
set all_temp;  /* shewjen - all to all_temp */

%macro urs(t);

   if ( (Acct_status in ("&t")) & (s01 not in ("&t")) )
then mos_last_&t =0;

else if ( (s01="&t") & (s02 not in ("&t")) )
then mos_last_&t =1;

else if ( (s02="&t") & (s03 not in ("&t")) )
then mos_last_&t =2;

else if ( (s03="&t") & (s04 not in ("&t")) )
then mos_last_&t =3;

else if ( (s04="&t") & (s05 not in ("&t")) )
then mos_last_&t =4;

else if ( (s05="&t") & (s06 not in ("&t")) )
then mos_last_&t =5;

else if ( (s06="&t") & (s07 not in ("&t")) )
then mos_last_&t =6;

else if ( (s07="&t") & (s08 not in ("&t")) )
then mos_last_&t =7;

else if ( (s08="&t") & (s09 not in ("&t")) )
then mos_last_&t =8;

else if ( (s09="&t") & (s10 not in ("&t")) )
then mos_last_&t =9;

else if ( (s10="&t") & (s11 not in ("&t")) )
then mos_last_&t =10;

else if ( (s11="&t") & (s12 not in ("&t")) )
then mos_last_&t =11;

else if ( (s12="&t") & (s13 not in ("&t")) )
then mos_last_&t =12;

else if ( (s13="&t") & (s14 not in ("&t")) )
then mos_last_&t =13;

else if ( (s14="&t") & (s15 not in ("&t")) )
then mos_last_&t =14;

else if ( (s15="&t") & (s16 not in ("&t")) )
then mos_last_&t =15;

else if ( (s16="&t") & (s17 not in ("&t")) )
then mos_last_&t =16;

else if ( (s17="&t") & (s18 not in ("&t")) )
then mos_last_&t =17;

else if ( (s18="&t") & (s19 not in ("&t")) )
then mos_last_&t =18;

else if ( (s19="&t") & (s20 not in ("&t")) )
then mos_last_&t =19;

else if ( (s20="&t") & (s21 not in ("&t")) )
then mos_last_&t =20;

else if ( (s21="&t") & (s22 not in ("&t")) )
then mos_last_&t =21;

else if ( (s22="&t") & (s23 not in ("&t")) )
then mos_last_&t =22;

else if ( (s23="&t") & (s24 not in ("&t")) )
then mos_last_&t =23;

else if (s24="&t")
then mos_last_&t =24;

if mos_last_&t=. then mos_last_&t=995;
if mos_since_reported=999 then mos_last_&t=997;

%mend;

*** mos_last_9,mos_last_F,mos_last_U,mos_last_P,mos_last_N,mos_last_B ***;
%urs(9);
%urs(F);
%urs(U);
%urs(P);
%urs(N);
%urs(B);

*** months since rate code ******;
%macro rt(rate);
/*
if indexc(acct_status,"&rate")=0 and Curr_Bal_dt=. then age_&rate=995;
else if indexc(S01,"&rate")=0 and DT01=. then age_&rate=995;
else if indexc(S02,"&rate")=0 and DT02=. then age_&rate=995;
else if indexc(S03,"&rate")=0 and DT03=. then age_&rate=995;
else if indexc(S04,"&rate")=0 and DT04=. then age_&rate=995;
else if indexc(S05,"&rate")=0 and DT05=. then age_&rate=995;
else if indexc(S06,"&rate")=0 and DT06=. then age_&rate=995;
else if indexc(S07,"&rate")=0 and DT07=. then age_&rate=995;
else if indexc(S08,"&rate")=0 and DT08=. then age_&rate=995;
else if indexc(S09,"&rate")=0 and DT09=. then age_&rate=995;
else if indexc(S10,"&rate")=0 and DT10=. then age_&rate=995;
else if indexc(S11,"&rate")=0 and DT11=. then age_&rate=995;
else if indexc(S12,"&rate")=0 and DT12=. then age_&rate=995;
else if indexc(S13,"&rate")=0 and DT13=. then age_&rate=995;
else if indexc(S14,"&rate")=0 and DT14=. then age_&rate=995;
else if indexc(S15,"&rate")=0 and DT15=. then age_&rate=995;
else if indexc(S16,"&rate")=0 and DT16=. then age_&rate=995;
else if indexc(S17,"&rate")=0 and DT17=. then age_&rate=995;
else if indexc(S18,"&rate")=0 and DT18=. then age_&rate=995;
else if indexc(S19,"&rate")=0 and DT19=. then age_&rate=995;
else if indexc(S20,"&rate")=0 and DT20=. then age_&rate=995;
else if indexc(S21,"&rate")=0 and DT21=. then age_&rate=995;
else if indexc(S22,"&rate")=0 and DT22=. then age_&rate=995;
else if indexc(S23,"&rate")=0 and DT23=. then age_&rate=995;
else if indexc(S24,"&rate")=0 and DT24=. then age_&rate=995;
*/

if indexc(acct_status,"&rate") ne 0 then age_&rate=0;
else if indexc(S01,"&rate") ne 0 then age_&rate=1;
else if indexc(S02,"&rate") ne 0 then age_&rate=2;
else if indexc(S03,"&rate") ne 0 then age_&rate=3;
else if indexc(S04,"&rate") ne 0 then age_&rate=4;
else if indexc(S05,"&rate") ne 0 then age_&rate=5;
else if indexc(S06,"&rate") ne 0 then age_&rate=6;
else if indexc(S07,"&rate") ne 0 then age_&rate=7;
else if indexc(S08,"&rate") ne 0 then age_&rate=8;
else if indexc(S09,"&rate") ne 0 then age_&rate=9;
else if indexc(S10,"&rate") ne 0 then age_&rate=10;
else if indexc(S11,"&rate") ne 0 then age_&rate=11;
else if indexc(S12,"&rate") ne 0 then age_&rate=12;
else if indexc(S13,"&rate") ne 0 then age_&rate=13;
else if indexc(S14,"&rate") ne 0 then age_&rate=14;
else if indexc(S15,"&rate") ne 0 then age_&rate=15;
else if indexc(S16,"&rate") ne 0 then age_&rate=16;
else if indexc(S17,"&rate") ne 0 then age_&rate=17;
else if indexc(S18,"&rate") ne 0 then age_&rate=18;
else if indexc(S19,"&rate") ne 0 then age_&rate=19;
else if indexc(S20,"&rate") ne 0 then age_&rate=20;
else if indexc(S21,"&rate") ne 0 then age_&rate=21;
else if indexc(S22,"&rate") ne 0 then age_&rate=22;
else if indexc(S23,"&rate") ne 0 then age_&rate=23;
else if indexc(S24,"&rate") ne 0 then age_&rate=24;
else age_&rate=995;
%mend;

%rt(0);
%rt(123456);
%rt(23456);
%rt(3456);

if cnxid=' ' then do;
   age_0=999;
end;
else if cnxid ne ' ' and age_0=995 then age_0=995;

else if cnxid ne ' ' and age_0 <= 992 then do;
   age_0=age_0;
end;

if cnxid=' ' then do;
   age_1p=999;
end;
else if cnxid ne ' ' and age_123456=995 then age_1p=995;

else if cnxid ne ' ' and age_1p <= 992 then do;
   age_1p=age_123456;
end;
if cnxid=' ' then do;
   age_1p_unpaid=999;
end;
else if cnxid ne ' ' and (age_123456=995 & mos_last_N=995 & mos_last_P=995 & mos_last_U=995 ) then  age_1p_unpaid=995;

else if cnxid ne ' ' and age_1p_unpaid <= 992 then do;
   age_1p_unpaid=min(age_123456,mos_last_N,mos_last_P,mos_last_U);
end;
if cnxid=' ' then do;
   age_2p=999;
end;
else if cnxid ne ' ' and age_23456=995 then age_2p=995;

else if cnxid ne ' ' and age_2p <= 992 then do;
   age_2p=age_23456;
end;
if cnxid=' ' then do;
   age_2p_unpaid=999;
end;
else if cnxid ne ' ' and (age_23456=995 & mos_last_N=995 & mos_last_P=995 & mos_last_U=995 ) then age_2p_unpaid=995;

else if cnxid ne ' ' and age_2p_unpaid <= 992 then do;
   age_2p_unpaid=min(age_23456,mos_last_N,mos_last_P,mos_last_U);
end;
if cnxid=' ' then do;
   age_3p=999;
end;
else if cnxid ne ' ' and age_3456=995 then age_3p=995;

else if cnxid ne ' ' and age_3p <= 992 then do;
   age_3p=age_3456;
end;
if cnxid=' ' then do;
   age_3p_unpaid=999;
end;
else if cnxid ne ' ' and (age_3456=995 & mos_last_N=995 & mos_last_P=995 & mos_last_U=995 ) then age_3p_unpaid=995;

else if cnxid ne ' ' and age_3p_unpaid <= 992 then do;
   age_3p_unpaid=min(age_3456,mos_last_N,mos_last_P,mos_last_U);
end;
if cnxid=' ' then do;
   age_unpaid=999;
end;
else if cnxid ne ' ' and (mos_last_N=995 & mos_last_P=995 & mos_last_U=995) then age_unpaid=995;

else if cnxid ne ' ' and age_unpaid <= 992 then do;
   age_unpaid=min(mos_last_N,mos_last_P,mos_last_U);
end;

run;

Data xy6;
set xy6;
;
keep cnxid Acct_status s01 s02 s03 s04 s05 s06 s07 s08 s09 s10 s11 
     S12 S13 S14 S15 S16 S17 S18 S19 S20 S21 S22 S23 S24 Curr_Bal_dt dt01 dt02 dt03 dt04 dt05 dt06 dt07 dt08 dt09 dt10
     dt11 dt12 dt13 dt14 dt15 dt16 dt17 dt18 dt19 dt20 dt21 dt22 dt23 dt24
     age_0 age_123456 age_23456 age_3456 age_1p age_2p age_3p age_1p_unpaid age_2p_unpaid age_3p_unpaid age_unpaid
     mos_last_F mos_last_9 mos_last_N mos_last_P mos_last_U mos_last_B
;
run;

Data xy71;
set all_temp;   /* shewjen - all to all_temp */
closed3=(
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6')) 
                         )
;
closed6=(
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6')) and
                         (s03 not in ('0','1','2','3','4','5','6')) and
                         (s04 not in ('0','1','2','3','4','5','6')) and
                         (s05 not in ('0','1','2','3','4','5','6'))
                         )
;
closed12=(
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6')) and
                         (s03 not in ('0','1','2','3','4','5','6')) and
                         (s04 not in ('0','1','2','3','4','5','6')) and
                         (s05 not in ('0','1','2','3','4','5','6')) and
                         (s06 not in ('0','1','2','3','4','5','6')) and
                         (s07 not in ('0','1','2','3','4','5','6')) and
                         (s08 not in ('0','1','2','3','4','5','6')) and
                         (s09 not in ('0','1','2','3','4','5','6')) and
                         (s10 not in ('0','1','2','3','4','5','6')) and
                         (s11 not in ('0','1','2','3','4','5','6'))
                         )
;
run;

proc sort data=xy71 out=xy71;
by cnxid descending mos_since_reported descending closed3 descending closed6 descending closed12;
run;

proc sort data=all_temp out=xy72;  /* shewjen - all to all_temp */
by cnxid descending mos_since_reported Curr_bal bal01 bal02 bal03 bal04 bal05;
run;

proc sort data=all_temp out=xy73;  /* shewjen - all to all_temp */
by cnxid descending mos_since_reported Pmt_Amt PMT01;
run;

Data xy74;
set all_temp;  /* shewjen - all to all_temp */

last_status_x=(last_status not in ('U','B','N','P'));

run;

proc sort data=xy74 out=xy74;
by cnxid descending mos_since_reported descending last_status_x;
run;

Data xy74;
set xy74;
by cnxid;

if (first.cnxid) then do;
   tot_cls_unpaid_bal_rep_6_t=.;
end;

******* total closed unpaid balance rep in 6 months **********;
if cnxid=' ' then tot_cls_unpaid_bal_rep_6_t=999999;
else if cnxid ne ' ' and (mos_since_reported > 5) then tot_cls_unpaid_bal_rep_6_t=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and
     ( (Curr_bal=. and bal01=. and bal02=. and bal03=. and bal04=. and bal05=.)|(last_status not in ('U','B','N','P')) )
                     then do;
   if tot_cls_unpaid_bal_rep_6_t=999997 then tot_cls_unpaid_bal_rep_6_t=999995;
   else tot_cls_unpaid_bal_rep_6_t=999995;
end;
else if cnxid ne ' ' and (0 <=mos_since_reported<= 5) and (last_status in ('U','B','N','P'))  then do;
   if tot_cls_unpaid_bal_rep_6_t=999997 then tot_cls_unpaid_bal_rep_6_t=0;
   if tot_cls_unpaid_bal_rep_6_t=999995 then tot_cls_unpaid_bal_rep_6_t=0;
   if tot_cls_unpaid_bal_rep_6_t <= 999992 then do;
      if Curr_bal ne . then do;
         tot_cls_unpaid_bal_rep_6_t=Curr_bal;
      end;
      else if Curr_bal=. then do;
         if (dt01 ne . and bal01 ne .) then do;
            tot_cls_unpaid_bal_rep_6_t=bal01;
         end;
         else if (dt02 ne . and bal02 ne .) then do;
            tot_cls_unpaid_bal_rep_6_t=bal02;
         end;
         else if (dt03 ne . and bal03 ne .) then do;
            tot_cls_unpaid_bal_rep_6_t=bal03;
         end;
         else if (dt04 ne . and bal04 ne .) then do;
            tot_cls_unpaid_bal_rep_6_t=bal04;
         end;
         else if (dt05 ne . and bal05 ne .) then do;
            tot_cls_unpaid_bal_rep_6_t=bal05;
         end;
      end;
   end;
end;

run;


Data xy73;
set xy73;
by cnxid;

if (first.cnxid) then do;
   curpay_t=.;
end;

***     TOT0801 -       Sum of Current Month Payments ***;
if cnxid=' ' then curpay_t=999999;
else if cnxid ne ' ' and (mos_since_reported > 1) then curpay_t=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) and (Pmt_Amt=. and PMT01=.) then do;
   if curpay_t=999997 then curpay_t=999995;
   else curpay_t=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) and (Pmt_Amt ne .|PMT01 ne .) then do;
   if curpay_t=999997 then curpay_t=0;
   if curpay_t=999995 then curpay_t=0;
   if curpay_t <= 999992 then do;
      if (0 <= mos_since_reported <= 1) then do;
         if Pmt_Amt ne . then do;
            curpay_t=Pmt_Amt;
         end;
         else if Pmt_Amt=. then do;
            if (dt01 ne . and PMT01 ne .) then do;
               curpay_t=PMT01;
            end;
         end;
     end;
   end;
end;

run;

Data xy72;
set xy72;
by cnxid;

if (first.cnxid) then do;
   curbal_t=.;
   tot_bal_rep_6_t=.;
end;

***     TOT0403 -       Sum of Current Month Balances  ***;
if cnxid=' ' then curbal_t=999999;
else if cnxid ne ' ' and (mos_since_reported > 1) then curbal_t=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) and (Curr_bal=. and bal01=.) then do;
   if curbal_t=999997 then curbal_t=999995;
   else curbal_t=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) and (Curr_bal ne .|bal01 ne .) then do;
   if curbal_t=999997 then curbal_t=0;
   if curbal_t=999995 then curbal_t=0;
   if curbal_t <= 999992 then do;
      if (0 <= mos_since_reported <= 1) then do;
         if Curr_bal ne . then do;
            curbal_t=Curr_bal;
         end;
         else if Curr_bal=. then do;
            if (dt01 ne . and bal01 ne .) then do;
               curbal_t=bal01;
            end;
         end;
      end;
   end;

end;

***     TOT0401 -       Sum of Current Balances Reported in Last 6 Months  ***;
if cnxid=' ' then tot_bal_rep_6_t=999999;
else if cnxid ne ' ' and (mos_since_reported > 5) then tot_bal_rep_6_t=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and (Curr_bal=. and bal01=. and bal02=. and bal03=. and bal04=. and bal05=.) then do;
   if tot_bal_rep_6_t=999997 then tot_bal_rep_6_t=999995;
   else tot_bal_rep_6_t=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and (Curr_bal ne .|bal01 ne .| bal02 ne .|bal03 ne .|bal04 ne .|bal05 ne .) then do;
   if tot_bal_rep_6_t=999997 then tot_bal_rep_6_t=0;
   if tot_bal_rep_6_t=999995 then tot_bal_rep_6_t=0;
   if tot_bal_rep_6_t <= 999992 then do;
      if (0 <=mos_since_reported<= 5) then do;
         if Curr_bal ne . then do;
            tot_bal_rep_6_t=Curr_bal;
         end;
         else if Curr_bal=. then do;
            if (dt01 ne . and bal01 ne .) then do;
               tot_bal_rep_6_t=bal01;
            end;
            else if (dt02 ne . and bal02 ne .) then do;
               tot_bal_rep_6_t=bal02;
            end;
            else if (dt03 ne . and bal03 ne .) then do;
               tot_bal_rep_6_t=bal03;
            end;
            else if (dt04 ne . and bal04 ne .) then do;
               tot_bal_rep_6_t=bal04;
            end;
            else if (dt05 ne . and bal05 ne .) then do;
               tot_bal_rep_6_t=bal05;
            end;
         end;
      end;
   end;
end;

run;


Data xy71;
set xy71;
by cnxid;

if (first.cnxid) then do;
   avg_bal_3=.;
   avg_bal_6=.;
   avg_bal_12=.;
   max_bal_rep_6=.;
   tot_open_bal_t=.;
   n_open_3=0;
   n_open_3_1=0;
   n_open_6=0;
   n_open_6_1=0;
   n_open_12=0;
   n_open_12_1=0;
end;

***     TOT0402 -       Sum of Open Current Month Balances  ***;
if cnxid=' ' then tot_open_bal_t=999999;
else if cnxid ne ' ' and (mos_since_reported > 1) then tot_open_bal_t=999997;
else if cnxid ne ' ' and  (0 <= mos_since_reported <= 1) and
                          ( 
                          (Acct_status not in ('0','1','2','3','4','5','6'))
                          and
                          (S01 not in ('0','1','2','3','4','5','6'))
                          )
                          then do;
   if tot_open_bal_t=999997 then tot_open_bal_t=999996;
   else tot_open_bal_t=999996;
end;
else if cnxid ne ' ' and  (0 <= mos_since_reported <= 1) and
                          (
                          (Acct_status in ('0','1','2','3','4','5','6'))
                          |
                          (S01 in ('0','1','2','3','4','5','6'))
                          )
                          and (Curr_bal=. and bal01=. ) then do;
   if tot_open_bal_t=999997 then tot_open_bal_t=999995;
   if tot_open_bal_t=999996 then tot_open_bal_t=999995;
   else tot_open_bal_t=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) and (Curr_bal ne .|bal01 ne .) then do;
   if tot_open_bal_t=999997 then tot_open_bal_t=0;
   if tot_open_bal_t=999996 then tot_open_bal_t=0;
   if tot_open_bal_t=999995 then tot_open_bal_t=0;
   if tot_open_bal_t <= 999992 then do;
      if (0 <= mos_since_reported <= 1) then do;
         if Curr_bal ne . then do;
            if (Acct_status in ('0','1','2','3','4','5','6')) then tot_open_bal_t=Curr_bal;
         end;
         else if Curr_bal=. then do;
            if (dt01 ne . and bal01 ne .) then do;
               if (S01 in ('0','1','2','3','4','5','6')) then tot_open_bal_t=bal01;
            end;
         end;
      end;
   end;
end;
if tot_open_bal_t=. then tot_open_bal_t=999994;

*** Number of open accounts Tradeline level *********;
n_open_c_12=0;
n_open_s01_12=0;
n_open_s02_12=0;
n_open_s03_12=0;
n_open_s04_12=0;
n_open_s05_12=0;
n_open_s06_12=0;
n_open_s07_12=0;
n_open_s08_12=0;
n_open_s09_12=0;
n_open_s10_12=0;
n_open_s11_12=0;

if (Acct_status in ('0','1','2','3','4','5','6')) then n_open_c_12+1;
if (s01 in ('0','1','2','3','4','5','6')) then n_open_s01_12+1;
if (s02 in ('0','1','2','3','4','5','6')) then n_open_s02_12+1;
if (s03 in ('0','1','2','3','4','5','6')) then n_open_s03_12+1;
if (s04 in ('0','1','2','3','4','5','6')) then n_open_s04_12+1;
if (s05 in ('0','1','2','3','4','5','6')) then n_open_s05_12+1;
if (s06 in ('0','1','2','3','4','5','6')) then n_open_s06_12+1;
if (s07 in ('0','1','2','3','4','5','6')) then n_open_s07_12+1;
if (s08 in ('0','1','2','3','4','5','6')) then n_open_s08_12+1;
if (s09 in ('0','1','2','3','4','5','6')) then n_open_s09_12+1;
if (s10 in ('0','1','2','3','4','5','6')) then n_open_s10_12+1;
if (s11 in ('0','1','2','3','4','5','6')) then n_open_s11_12+1;

if (0 <= mos_since_reported <= 2) then do;
 n_open_3=sum(of n_open_c_12 n_open_s01_12 n_open_s02_12);
 if n_open_3 > 0 then n_open_3_1+1;
end;

if (0 <= mos_since_reported <= 5) then do;
 n_open_6=sum(of n_open_c_12 n_open_s01_12 n_open_s02_12 n_open_s03_12 n_open_s04_12 n_open_s05_12);
 if n_open_6 > 0 then n_open_6_1+1;
end;

if (0 <= mos_since_reported <= 11) then do;
 n_open_12=sum(of n_open_c_12 n_open_s01_12 n_open_s02_12 n_open_s03_12 n_open_s04_12 n_open_s05_12
                 n_open_s06_12 n_open_s07_12 n_open_s08_12 n_open_s09_12 n_open_s10_12 n_open_s11_12);
 if n_open_12 > 0 then n_open_12_1+1;
end;

*** Total balance Tradeline level open accounts ********;

if (Acct_status in ('0','1','2','3','4','5','6')) then currbal_12=Curr_bal;
if (s01 in ('0','1','2','3','4','5','6')) then bal01_12=BAL01;
if (s02 in ('0','1','2','3','4','5','6')) then bal02_12=BAL02;
if (s03 in ('0','1','2','3','4','5','6')) then bal03_12=BAL03;
if (s04 in ('0','1','2','3','4','5','6')) then bal04_12=BAL04;
if (s05 in ('0','1','2','3','4','5','6')) then bal05_12=BAL05;
if (s06 in ('0','1','2','3','4','5','6')) then bal06_12=BAL06;
if (s07 in ('0','1','2','3','4','5','6')) then bal07_12=BAL07;
if (s08 in ('0','1','2','3','4','5','6')) then bal08_12=BAL08;
if (s09 in ('0','1','2','3','4','5','6')) then bal09_12=BAL09;
if (s10 in ('0','1','2','3','4','5','6')) then bal10_12=BAL10;
if (s11 in ('0','1','2','3','4','5','6')) then bal11_12=BAL11;

if (0 <= mos_since_reported <= 2) then do;
 bal_3=sum(of currbal_12 bal01_12 bal02_12);
end;

if (0 <= mos_since_reported <= 5) then do;
 bal_6=sum(of currbal_12 bal01_12 bal02_12 bal03_12 bal04_12 bal05_12);
end;

if (0 <= mos_since_reported <= 11) then do;
 bal_12=sum(of currbal_12 bal01_12 bal02_12 bal03_12 bal04_12 bal05_12 bal06_12 bal07_12 bal08_12 bal09_12 bal10_12 bal11_12);
end;

******* Average balance Tradeline level open accounts *********;
if cnxid=' ' then avg_bal_3=999999;
else if cnxid ne ' ' and (mos_since_reported > 2) then avg_bal_3=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and
                         (
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6'))
                         ) 
                         then do;
   if avg_bal_3=999997 then avg_bal_3=999996;
   else avg_bal_3=999996;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))
                         )
                         and (currbal_12=. & bal01_12=. & bal02_12=.) then do;
   if avg_bal_3=999997 then avg_bal_3=999995;
   else if avg_bal_3=999996 then avg_bal_3=999995;
   else avg_bal_3=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))
                         )
                         then do;
   if (bal_3=.|n_open_3=.|n_open_3=0) then do;
      if avg_bal_3=999997 then avg_bal_3=999994;
      else if avg_bal_3=999996 then avg_bal_3=999994;
      else if avg_bal_3=999995 then avg_bal_3=999994;
      else avg_bal_3=999994;
   end;
   else if (bal_3=0 & n_open_3>0) then avg_bal_3=0;
   else if ( (bal_3>0|bal_3<0) & n_open_3>0) then do;
      if avg_bal_3=999997 then avg_bal_3=0;
      if avg_bal_3=999996 then avg_bal_3=0;
      if avg_bal_3=999995 then avg_bal_3=0;
      if avg_bal_3=999994 then avg_bal_3=0;
      if avg_bal_3 <= 999992 then do;
         if n_open_3 > 0 then avg_bal_3t=(bal_3/n_open_3);
             
      end;
   end;
end;
if (avg_bal_3 > 999992) then avg_bal_3t=avg_bal_3;
if (avg_bal_3 = 0) then avg_bal_3t=avg_bal_3;

if cnxid=' ' then avg_bal_6=999999;
else if cnxid ne ' ' and (mos_since_reported > 5) then avg_bal_6=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and
                         (
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6')) and
                         (s03 not in ('0','1','2','3','4','5','6')) and
                         (s04 not in ('0','1','2','3','4','5','6')) and
                         (s05 not in ('0','1','2','3','4','5','6'))
                         ) 
                         then do;
   if avg_bal_6=999997 then avg_bal_6=999996;
   else avg_bal_6=999996;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))| 
                         (s03 in ('0','1','2','3','4','5','6'))| 
                         (s04 in ('0','1','2','3','4','5','6'))| 
                         (s05 in ('0','1','2','3','4','5','6'))
                         )
                         and (currbal_12=. & bal01_12=. & bal02_12=. & bal03_12=. & bal04_12=. & bal05_12=.) then do;
   if avg_bal_6=999997 then avg_bal_6=999995;
   if avg_bal_6=999996 then avg_bal_6=999995;
   else avg_bal_6=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and 
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))|
                         (s03 in ('0','1','2','3','4','5','6'))|
                         (s04 in ('0','1','2','3','4','5','6'))|
                         (s05 in ('0','1','2','3','4','5','6'))
                         )
                         then do;
   if (bal_6=.|n_open_6=.|n_open_6=0) then do;
      if avg_bal_6=999997 then avg_bal_6=999994;
      else if avg_bal_6=999996 then avg_bal_6=999994;
      else if avg_bal_6=999995 then avg_bal_6=999994;
      else avg_bal_6=999994;
   end;
   else if (bal_6=0 & n_open_6>0) then avg_bal_6=0;
   else if ( (bal_6>0|bal_6<0) & n_open_6>0) then do;
      if avg_bal_6=999997 then avg_bal_6=0;
      if avg_bal_6=999996 then avg_bal_6=0;
      if avg_bal_6=999995 then avg_bal_6=0;
      if avg_bal_6=999994 then avg_bal_6=0;
      if n_open_6 > 0 then avg_bal_6t=(bal_6/n_open_6);
             
   end;
end;
if (avg_bal_6 > 999992) then avg_bal_6t=avg_bal_6;
if (avg_bal_6 = 0) then avg_bal_6t=avg_bal_6;

if cnxid=' ' then avg_bal_12=999999;
else if cnxid ne ' ' and (mos_since_reported > 11) then avg_bal_12=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and
                         (
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6')) and
                         (s03 not in ('0','1','2','3','4','5','6')) and
                         (s04 not in ('0','1','2','3','4','5','6')) and
                         (s05 not in ('0','1','2','3','4','5','6')) and
                         (s06 not in ('0','1','2','3','4','5','6')) and
                         (s07 not in ('0','1','2','3','4','5','6')) and
                         (s08 not in ('0','1','2','3','4','5','6')) and
                         (s09 not in ('0','1','2','3','4','5','6')) and
                         (s10 not in ('0','1','2','3','4','5','6')) and
                         (s11 not in ('0','1','2','3','4','5','6')) 
                         ) 
                         then do;
  if avg_bal_12=999997 then avg_bal_12=999996;
  else avg_bal_12=999996;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))| 
                         (s03 in ('0','1','2','3','4','5','6'))| 
                         (s04 in ('0','1','2','3','4','5','6'))|
                         (s05 in ('0','1','2','3','4','5','6'))| 
                         (s06 in ('0','1','2','3','4','5','6'))| 
                         (s07 in ('0','1','2','3','4','5','6'))| 
                         (s08 in ('0','1','2','3','4','5','6'))|
                         (s09 in ('0','1','2','3','4','5','6'))|
                         (s10 in ('0','1','2','3','4','5','6'))|
                         (s11 in ('0','1','2','3','4','5','6'))
                         )
                         and (currbal_12=. & bal01_12=. & bal02_12=. & bal03_12=. & bal04_12=. & bal05_12=. & bal06_12=. & bal07_12=.
                              & bal08_12=. & bal09_12=. & bal10_12=. & bal11_12=.) then do; 
   if avg_bal_12=999997 then avg_bal_12=999995;
   if avg_bal_12=999996 then avg_bal_12=999995;
   else avg_bal_12=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and 
                     (
                         (Acct_status in ('0','1','2','3','4','5','6'))|
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))| 
                         (s03 in ('0','1','2','3','4','5','6'))| 
                         (s04 in ('0','1','2','3','4','5','6'))|
                         (s05 in ('0','1','2','3','4','5','6'))| 
                         (s06 in ('0','1','2','3','4','5','6'))| 
                         (s07 in ('0','1','2','3','4','5','6'))|
                         (s08 in ('0','1','2','3','4','5','6'))|
                         (s09 in ('0','1','2','3','4','5','6'))| 
                         (s10 in ('0','1','2','3','4','5','6'))| 
                         (s11 in ('0','1','2','3','4','5','6'))
                         )
                         then do;
   if (bal_12=.|n_open_12=.|n_open_12=0) then do;
      if avg_bal_12=999997 then avg_bal_12=999994;
      else if avg_bal_12=999996 then avg_bal_12=999994;
      else if avg_bal_12=999995 then avg_bal_12=999994;
      else avg_bal_12=999994;
   end;
   else if (bal_12=0 & n_open_12>0) then avg_bal_12=0;
   else if ( (bal_12>0|bal_12<0) & n_open_12>0) then do;
      if avg_bal_12=999997 then avg_bal_12=0;
      if avg_bal_12=999995 then avg_bal_12=0;
      if avg_bal_12=999996 then avg_bal_12=0;
      if avg_bal_12=999994 then avg_bal_12=0;
      if avg_bal_12 <= 999992 then do;
         if n_open_12 > 0 then avg_bal_12t=(bal_12/n_open_12);
             
      end;
   end;
end;
if (avg_bal_12 > 999992) then avg_bal_12t=avg_bal_12;
if (avg_bal_12 = 0) then avg_bal_12t=avg_bal_12;

**** max open balance in 3,6,12 months ****;
if cnxid=' ' then max_open_bal_3=999999;
else if cnxid ne ' ' and (mos_since_reported > 2) then max_open_bal_3=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and
                         (
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6'))
                         ) then do;
   if max_open_bal_3=999997 then max_open_bal_3=999996;
   else  max_open_bal_3=999996;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))
                         ) and (currbal_12=. & bal01_12=. & bal02_12=.) then do;
   if max_open_bal_3=999997 then max_open_bal_3=999995;
   else if max_open_bal_3=999996 then max_open_bal_3=999995;
   else  max_open_bal_3=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 2) and 
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))
                         ) and 
                         (currbal_12 ne .|bal01_12 ne .|bal02_12 ne .) then do;
   if max_open_bal_3=999997 then max_open_bal_3=0;
   if max_open_bal_3=999996 then max_open_bal_3=0;
   if max_open_bal_3=999995 then max_open_bal_3=0;
   max_open_bal_3=max(currbal_12,bal01_12,bal02_12);
end;
if max_open_bal_3=. then max_open_bal_3=999994;

if cnxid=' ' then max_open_bal_6=999999;
else if cnxid ne ' ' and (mos_since_reported > 5) then max_open_bal_6=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and
                         (
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6')) and
                         (s03 not in ('0','1','2','3','4','5','6')) and
                         (s04 not in ('0','1','2','3','4','5','6')) and
                         (s05 not in ('0','1','2','3','4','5','6')) 
                         ) then do;
   if max_open_bal_6=999997 then max_open_bal_6=999996;
   else  max_open_bal_6=999996;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))| 
                         (s03 in ('0','1','2','3','4','5','6'))| 
                         (s04 in ('0','1','2','3','4','5','6'))| 
                         (s05 in ('0','1','2','3','4','5','6'))
                         )
                         and (currbal_12=. & bal01_12=. & bal02_12=. & bal03_12=. & bal04_12=. & bal05_12=.)
                         then do;
   if max_open_bal_6=999997 then max_open_bal_6=999995;
   else if max_open_bal_6=999996 then max_open_bal_6=999995;
   else  max_open_bal_6=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and 
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))| 
                         (s03 in ('0','1','2','3','4','5','6'))|
                         (s04 in ('0','1','2','3','4','5','6'))|
                         (s05 in ('0','1','2','3','4','5','6'))
                         )
                         and (currbal_12 ne .|bal01_12 ne .|bal02_12 ne .|bal03_12 ne .|bal04_12 ne .|bal05_12 ne .) then do;
   if max_open_bal_6=999997 then max_open_bal_6=0;
   if max_open_bal_6=999996 then max_open_bal_6=0;
   if max_open_bal_6=999995 then max_open_bal_6=0;
   max_open_bal_6=max(currbal_12,bal01_12,bal02_12,bal03_12,bal04_12,bal05_12);
end;
if max_open_bal_6=. then max_open_bal_6=999994;

if cnxid=' ' then max_open_bal_12=999999;
else if cnxid ne ' ' and (mos_since_reported > 11) then max_open_bal_12=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and
                         (
                         (Acct_status not in ('0','1','2','3','4','5','6')) and
                         (s01 not in ('0','1','2','3','4','5','6')) and
                         (s02 not in ('0','1','2','3','4','5','6')) and
                         (s03 not in ('0','1','2','3','4','5','6')) and
                         (s04 not in ('0','1','2','3','4','5','6')) and
                         (s05 not in ('0','1','2','3','4','5','6')) and
                         (s06 not in ('0','1','2','3','4','5','6')) and
                         (s07 not in ('0','1','2','3','4','5','6')) and
                         (s08 not in ('0','1','2','3','4','5','6')) and
                         (s09 not in ('0','1','2','3','4','5','6')) and
                         (s10 not in ('0','1','2','3','4','5','6')) and
                         (s11 not in ('0','1','2','3','4','5','6')) 
                         ) then do;
   if max_open_bal_12=999997 then max_open_bal_12=999996;
   else  max_open_bal_12=999996;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and
                         (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))| 
                         (s03 in ('0','1','2','3','4','5','6'))| 
                         (s04 in ('0','1','2','3','4','5','6'))| 
                         (s05 in ('0','1','2','3','4','5','6'))| 
                         (s06 in ('0','1','2','3','4','5','6'))|
                         (s07 in ('0','1','2','3','4','5','6'))|
                         (s08 in ('0','1','2','3','4','5','6'))|
                         (s09 in ('0','1','2','3','4','5','6'))|
                         (s10 in ('0','1','2','3','4','5','6'))|
                         (s11 in ('0','1','2','3','4','5','6'))
                         ) and
                         (currbal_12=. & bal01_12=. & bal02_12=. & bal03_12=. & bal04_12=. & bal05_12=. & bal06_12=. & bal07_12=. & bal08_12=.
                        & bal09_12=. & bal10_12=. & bal11_12=.)
                         then do;
   if max_open_bal_12=999997 then max_open_bal_12=999995;
   else if max_open_bal_12=999996 then max_open_bal_12=999995;
   else  max_open_bal_12=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 11) and 
                        (
                         (Acct_status in ('0','1','2','3','4','5','6'))| 
                         (s01 in ('0','1','2','3','4','5','6'))| 
                         (s02 in ('0','1','2','3','4','5','6'))| 
                         (s03 in ('0','1','2','3','4','5','6'))| 
                         (s04 in ('0','1','2','3','4','5','6'))| 
                         (s05 in ('0','1','2','3','4','5','6'))| 
                         (s06 in ('0','1','2','3','4','5','6'))|
                         (s07 in ('0','1','2','3','4','5','6'))|
                         (s08 in ('0','1','2','3','4','5','6'))|
                         (s09 in ('0','1','2','3','4','5','6'))|
                         (s10 in ('0','1','2','3','4','5','6'))|
                         (s11 in ('0','1','2','3','4','5','6'))
                         ) and
     (currbal_12 ne .|bal01_12 ne .|bal02_12 ne .|bal03_12 ne .|bal04_12 ne .|bal05_12 ne .|bal06_12 ne .|bal07_12 ne .|bal08_12 ne .|bal09_12 ne .|
      bal10_12 ne .|bal11_12 ne .) then do;
   if max_open_bal_12=999997 then max_open_bal_12=0;
   if max_open_bal_12=999996 then max_open_bal_12=0;
   if max_open_bal_12=999995 then max_open_bal_12=0;
   max_open_bal_12=max(currbal_12,bal01_12,bal02_12,bal03_12,bal04_12,bal05_12,bal06_12,bal07_12,bal08_12,bal09_12,bal10_12,bal11_12);
end;
if max_open_bal_12=. then max_open_bal_12=999994;

**** MAX of Current / Last rep balances in 6 months ********;
if cnxid=' ' then max_bal_rep_6=999999;
else if cnxid ne ' ' and (mos_since_reported > 5) then max_bal_rep_6=999997;
else if cnxid ne ' ' and (0 <=mos_since_reported<= 5) and (Curr_bal=. & bal01=. & bal02=. & bal03=. & bal04=. & bal05=.) then do;
   if max_bal_rep_6=999997 then max_bal_rep_6=999995;
   else max_bal_rep_6=999995;
end;
else if cnxid ne ' ' and (0 <=mos_since_reported<= 5) and ^(Curr_bal=. & bal01=. & bal02=. & bal03=. & bal04=. & bal05=.) then do;
   if max_bal_rep_6=999997 then max_bal_rep_6=0;
   if max_bal_rep_6=999995 then max_bal_rep_6=0;
   if Curr_bal ne . then do;
      max_bal_rep_6=Curr_bal;
   end;
   else if Curr_bal=. then do;
      if (dt01 ne . and bal01 ne .) then do;
         max_bal_rep_6=bal01;
      end;
      else if (dt02 ne . and bal02 ne .) then do;
          max_bal_rep_6=bal02;
      end;
      else if (dt03 ne . and bal03 ne .) then do;
          max_bal_rep_6=bal03;
      end;
      else if (dt04 ne . and bal04 ne .) then do;
          max_bal_rep_6=bal04;
      end;
      else if (dt05 ne . and bal05 ne .) then do;
          max_bal_rep_6=bal05;
      end;
   end;
end; 
if max_bal_rep_6=. then max_bal_rep_6=999994;

**** New Coding for attribute maxbal *****;
**** MAX of Current balances ********;
if cnxid=' ' then maxbal_1=999999;
else if cnxid ne ' ' and (mos_since_reported > 1) then maxbal_1=999997;
else if cnxid ne ' ' and (0 <=mos_since_reported<= 1) and (Curr_bal=. & bal01=. ) then do;
   if maxbal_1=999997 then maxbal_1=999995;
   else maxbal_1=999995;
end;
else if cnxid ne ' ' and (0 <=mos_since_reported<= 1) and ^(Curr_bal=. & bal01=. ) then do;
   if maxbal_1=999997 then maxbal_1=0;
   if maxbal_1=999995 then maxbal_1=0;
   if Curr_bal ne . then do;
      maxbal_1=Curr_bal;
   end;
   else if Curr_bal=. then do;
      if (dt01 ne . and bal01 ne .) then do;
         maxbal_1=bal01;
      end;
   end;
end;
if maxbal_1=. then maxbal_1=999994;

keep cnxid mos_since_reported Acct_status S01 S02 S03 S04 S05 S06 S07 S08 S09 S10 S11 
     Pmt_Amt PMT01 dt01 dt02 dt03 dt04 dt05 Curr_bal bal01 bal02 bal03 bal04 bal05 
     bal06 bal07 bal08 bal09 bal10 bal11 last_status tot_open_bal_t 
     bal_3 n_open_3 avg_bal_3t avg_bal_3
     bal_6 n_open_6 avg_bal_6t avg_bal_6 maxbal_1
     bal_12 n_open_12 avg_bal_12t avg_bal_12 max_open_bal_3 max_open_bal_6 max_open_bal_12
     currbal_12 bal01_12 bal02_12 bal03_12 bal04_12 bal05_12 bal06_12 bal07_12 bal08_12 bal09_12 bal10_12 bal11_12
     max_bal_rep_6 n_open_3_1 n_open_6_1 n_open_12_1
;
run;

proc sort data=all_temp out=xy8;   /* shewjen - all to all_temp */
by cnxid descending mos_since_reported Charge_off_amt CHG01 CHG02 CHG03 CHG04 CHG05;
run;

Data xy8;
set xy8;
by cnxid;

if (first.cnxid) then do;
   tot_choffamt_rep_6=.;
   curchoffamt=.;
end;

retain tot_choffamt_rep_6 curchoffamt;

**** Sum of Current / Last Reported Charge-Off Amount in 6 months ********;
if cnxid=' ' then tot_choffamt_rep_6=999999;
else if cnxid ne ' ' and (mos_since_reported > 5) then tot_choffamt_rep_6=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 5) and (Charge_off_amt=. & CHG01=. & CHG02=. & CHG03=. & CHG04=. & CHG05=.) then do;
   if tot_choffamt_rep_6=999997 then tot_choffamt_rep_6=999995;
   else tot_choffamt_rep_6=999995;
end;
else if cnxid ne ' ' and (0 <=mos_since_reported<= 5) and ^(Charge_off_amt=. & CHG01=. & CHG02=. & CHG03=. & CHG04=. & CHG05=.) then do;
   if tot_choffamt_rep_6=999997 then tot_choffamt_rep_6=0;
   if tot_choffamt_rep_6=999995 then tot_choffamt_rep_6=0;
   if Charge_off_amt ne . then do;
      tot_choffamt_rep_6=sum(tot_choffamt_rep_6,Charge_off_amt);
   end;
   else if Charge_off_amt=. then do;
      if (dt01 ne . and CHG01 ne .) then do;
         tot_choffamt_rep_6=sum(tot_choffamt_rep_6,CHG01);
      end;
      else if (dt02 ne . and CHG02 ne .) then do;
         tot_choffamt_rep_6=sum(tot_choffamt_rep_6,CHG02);
      end;
      else if (dt03 ne . and CHG03 ne .) then do;
         tot_choffamt_rep_6=sum(tot_choffamt_rep_6,CHG03);
      end;
      else if (dt04 ne . and CHG04 ne .) then do;
         tot_choffamt_rep_6=sum(tot_choffamt_rep_6,CHG04);
      end;
      else if (dt05 ne . and CHG05 ne .) then do;
         tot_choffamt_rep_6=sum(tot_choffamt_rep_6,CHG05);
      end;
   end;
end;

**** Sum of Current Month Charge-Off Amount ********;
if cnxid=' ' then curchoffamt=999999;
else if cnxid ne ' ' and (mos_since_reported > 1) then curchoffamt=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) and (Charge_off_amt=. & CHG01=.) then do;
   if curchoffamt=999997 then curchoffamt=999995;
   else curchoffamt=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) and ^(Charge_off_amt=. & CHG01=.) then do;
   if curchoffamt=999997 then curchoffamt=0;
   if curchoffamt=999995 then curchoffamt=0;
   if Charge_off_amt ne . then do;
      curchoffamt=sum(curchoffamt,Charge_off_amt);
   end;
   else if Charge_off_amt=. then do;
      if (dt01 ne . and CHG01 ne .) then do;
         curchoffamt=sum(curchoffamt,CHG01);
      end;
   end;

end;

if last.cnxid;

keep cnxid mos_since_reported Charge_off_amt CHG01 CHG02 CHG03 CHG04 CHG05
     dt01 dt02 dt03 dt04 dt05 tot_choffamt_rep_6 curchoffamt
;
run;

proc sort data=all_temp out=xy9;  /* shewjen - all to all_temp */
by cnxid mos_since_connected;
run;

Data xy9;
set xy9;
by cnxid;

if (first.cnxid) then do;
   age_avg_connect_1=.;
end;
retain age_avg_connect_1;
******* Avg Age of Connection ********;
if cnxid=' ' then age_avg_connect_1=999999;
else if cnxid ne ' ' and (mos_since_connected=.|mos_since_connected=999) then age_avg_connect_1=999997;
else if cnxid ne ' ' and (mos_since_connected ne .|mos_since_connected ne 999) then do;
   if age_avg_connect_1=999997 then age_avg_connect_1=0;
   age_avg_connect_1=sum(age_avg_connect_1,mos_since_connected);
end;

run;

proc sort data=all_temp out=xy10;   /* shewjen - all to all_temp */
by cnxid descending mos_since_disconnected;
run;

Data xy10;
set xy10;
by cnxid;

if (first.cnxid) then do;
   age_avg_disconnect_1=.;
end;
retain age_avg_disconnect_1;
******* Avg Age of Disconnection ********;
if cnxid=' ' then age_avg_disconnect_1=999999;
else if cnxid ne ' ' and (mos_since_disconnected=.|mos_since_disconnected=999) then age_avg_disconnect_1=999997;
else if cnxid ne ' ' and (mos_since_disconnected ne .|mos_since_disconnected ne 999) then do;
   if age_avg_disconnect_1=999997 then age_avg_disconnect_1=0;
   age_avg_disconnect_1=sum(age_avg_disconnect_1,mos_since_disconnected);
end;
if last.cnxid;
run;

proc sort data=all_temp out=xy11;  /* shewjen - all to all_temp */
by cnxid mos_since_disconnected descending last_status;
run;

Data xy11;
set xy11;
by cnxid;

if (first.cnxid) then do;
   age_avg_inv_disconnect_1=.;
end;

******* Avg Age of Involuntary Discoonnection ********;
if cnxid=' ' then age_avg_inv_disconnect_1=999;
else if cnxid ne ' ' and (mos_since_disconnected=.|mos_since_disconnected=999) then age_avg_inv_disconnect_1=997;
else if cnxid ne ' ' and ^(last_status in ('B','N','P','U') ) then do;
     if age_avg_inv_disconnect_1=997 then age_avg_inv_disconnect_1=995;
     else age_avg_inv_disconnect_1=995;
end;
else if cnxid ne ' ' and (mos_since_disconnected ne .|mos_since_disconnected ne 999) and (last_status in ('B','N','P','U') ) then do;
   if age_avg_inv_disconnect_1=997 then age_avg_inv_disconnect_1=0;
   if age_avg_inv_disconnect_1=995 then age_avg_inv_disconnect_1=0;
   if age_avg_inv_disconnect_1 <= 992 then age_avg_inv_disconnect_1+mos_since_disconnected;
end;

run;

proc sort data=all_temp out=xy12;  /* shewjen - all to all_temp */
by cnxid mos_since_disconnected descending last_status;
run;

Data xy12;
set xy12;
by cnxid;

if (first.cnxid) then do;
   age_avg_vol_disconnect_1=.;
end;

******* Avg Age of Voluntary Discoonnection ********;
if cnxid=' ' then age_avg_vol_disconnect_1=999;
else if cnxid ne ' ' and (mos_since_disconnected=.|mos_since_disconnected=999) then age_avg_vol_disconnect_1=997;
else if cnxid ne ' ' and ^(last_status not in (' ','B','N','P','U') ) then do;
     if age_avg_vol_disconnect_1=997 then age_avg_vol_disconnect_1=995;
     else age_avg_vol_disconnect_1=995;
end;
else if cnxid ne ' ' and (mos_since_disconnected ne .|mos_since_disconnected ne 999) and (last_status not in (' ','B','N','P','U') ) then do;
   if age_avg_vol_disconnect_1=997 then age_avg_vol_disconnect_1=0;
   if age_avg_vol_disconnect_1=995 then age_avg_vol_disconnect_1=0;
   if age_avg_vol_disconnect_1 <= 992 then age_avg_vol_disconnect_1+mos_since_disconnected;
end;

run;

proc sort data=all_temp out=xy13;  /* shewjen - all to all_temp */
by cnxid mos_since_reported ;
run;

Data xy13;
set xy13;
by cnxid;

if (first.cnxid) then do;
   cpaybal=.;
   avg_cpaybal_1=.;
end;

******* current payment to previous balance ratio ********;
if cnxid=' ' then cpaybal=999999;
else if cnxid ne ' ' and (mos_since_reported > 1) then cpaybal=999997;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) and ( Pmt_Amt=. & BAL01=. & PMT01=. & BAL02=. ) then do;
   if cpaybal=997 then cpaybal=999995;
   else cpaybal=999995;
end;
else if cnxid ne ' ' and (0 <= mos_since_reported <= 1) then do;
   if cpaybal=999997 then cpaybal=0;
   if cpaybal=999995 then cpaybal=0;
   else if .< BAL01 <= 0  then cpaybal=999994;
   else if BAL01 > 0 then cpaybal=round((Pmt_Amt/BAL01)*100,0.01);
   else if .< BAL02 <= 0  then cpaybal=999994;
   else if BAL02 > 0 then cpaybal=round((PMT01/BAL02)*100,0.01);
end;

   if cpaybal=999999 then avg_cpaybal_1=999999;
   else if cpaybal=999997 then avg_cpaybal_1=999997;
   else if cpaybal=999995 then avg_cpaybal_1=999995;
   else if cpaybal=999994 then avg_cpaybal_1=999994;
   else do;
      if avg_cpaybal_1 <= 999992 then avg_cpaybal_1+cpaybal;
   end;


if (0 <= cpaybal <= 999992) then n_cpay+1;

keep cnxid mos_since_reported Pmt_Amt BAL01 PMT01 BAL02 cpaybal avg_cpaybal_1 n_cpay;

run;

%macro rs(n,m);

Data tito&n.1;
set xy&n;
if (0 <= &m <= 92);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy&n;
if (&m > 92);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m; 
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid; 
run;

%mend;
%rs(0,num_accounts_rep_6);


%macro a(n,m);

Data tito&n.1;
set xy&n;
if (0 <= &m <= 992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy&n;
if (&m > 992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%a(1,age_connected2);
%a(2,age_0_connected2);
%a(3,age_disconnected2);

%macro a1(n,m);

Data tito&n.1;
set xy2;
if (0 <= &m <= 992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy2;
if (&m > 992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%a1(2a,age_0_connected2_6);

%macro b(n,m);

Data tito&n.1;
set xy4;
if (0 <= &m <= 992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy4;
if (&m > 992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%b(4,age_inv_disconnected2);
%b(5,age_vol_disconnected2);

%macro c(n,m);

Data tito&n.1;
set xy5;
if (0 <= &m <= 92);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy5;
if (&m > 92);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%c(6,num_0_wrst);
%c(7,num_0_wrst_3);
%c(8,num_0_wrst_6);
%c(9,num_0_wrst_12);
%c(10,num_1_wrst);
%c(11,num_1_wrst_3);
%c(12,num_1_wrst_6);
%c(13,num_1_wrst_12);
%c(14,num_2_wrst);
%c(15,num_2_wrst_3);
%c(16,num_2_wrst_6);
%c(17,num_2_wrst_12);
%c(18,num_2p_wrst);
%c(19,num_2p_wrst_3);
%c(20,num_2p_wrst_6);
%c(21,num_2p_wrst_12);
%c(22,num_2p_unpaid_wrst);
%c(23,num_2p_unpaid_wrst_3);
%c(24,num_2p_unpaid_wrst_6);
%c(25,num_2p_unpaid_wrst_12);
%c(26,num_3p_wrst);
%c(27,num_3p_wrst_3);
%c(28,num_3p_wrst_6);
%c(29,num_3p_wrst_12);
%c(30,num_3p_unpaid_wrst);
%c(31,num_3p_unpaid_wrst_3);
%c(32,num_3p_unpaid_wrst_6);
%c(33,num_3p_unpaid_wrst_12);
%c(34,num_0_3);
%c(35,num_0_6);
%c(36,num_0_12);
%c(37,num_1_3);
%c(38,num_1_6);
%c(39,num_1_12);
%c(40,num_2_3);
%c(41,num_2_6);
%c(42,num_2_12);

%macro d(n,m);

Data tito&n.1;
set xy6;
if (0 <= &m <= 992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy6;
if (&m > 992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%d(43,age_123456);
%d(44,age_23456);
%d(45,age_3456);
%d(46,age_1p);
%d(47,age_2p);
%d(48,age_3p);
%d(49,age_1p_unpaid);
%d(50,age_2p_unpaid);
%d(51,age_3p_unpaid);
%d(511,age_unpaid);

%macro ea(n,m);

Data tito&n.11
     tito&n.12
;
set xy73;
if (0 <= &m._t <= 999992) then output tito&n.11;
else if (&m._t < 0) then output tito&n.12;
run;

proc sort data=tito&n.11 out=tito&n.11(keep=cnxid &m._t);
by cnxid &m._t;
run;

proc sort data=tito&n.12 out=tito&n.12(keep=cnxid &m._t);
by cnxid &m._t;
run;

Data tito&n.2;
set xy73;
if (&m._t > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m._t);
by cnxid descending &m._t;
run;

Data tito&n;
set tito&n.2 tito&n.12 tito&n.11;
by cnxid;

if (first.cnxid) then do;
   &m=.;
end;

if (&m._t > 999992) then do;
   &m=&m._t;
end;
if (&m._t <= 999992) then do;
   if &m.=999997 then &m.=0;
   if &m.=999996 then &m.=0;
   if &m.=999995 then &m.=0;
   if &m.=999994 then &m.=0;
   &m.+&m._t;
end;

run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%ea(52,curpay);

%macro ei(n,m);

Data tito&n.11
     tito&n.12
;
set xy72;
if (0 <= &m._t <= 999992) then output tito&n.11;
else if (&m._t < 0) then output tito&n.12;
run;

proc sort data=tito&n.11 out=tito&n.11(keep=cnxid &m._t);
by cnxid &m._t;
run;

proc sort data=tito&n.12 out=tito&n.12(keep=cnxid &m._t);
by cnxid &m._t;
run;

Data tito&n.2;
set xy72;
if (&m._t > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m._t);
by cnxid descending &m._t;
run;

Data tito&n;
set tito&n.2 tito&n.12 tito&n.11;
by cnxid;

if (first.cnxid) then do;
   &m=.;
end;

if (&m._t > 999992) then do;
   &m=&m._t;
end;
if (&m._t <= 999992) then do;
   if &m.=999997 then &m.=0;
   if &m.=999996 then &m.=0;
   if &m.=999995 then &m.=0;
   if &m.=999994 then &m.=0;
   &m.+&m._t;
end;

run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%ei(53,curbal);
%ei(54,tot_bal_rep_6);


%macro en(n,m);

Data tito&n.11
     tito&n.12
;
set xy74;
if (0 <= &m._t <= 999992) then output tito&n.11;
else if (&m._t < 0) then output tito&n.12;
run;

proc sort data=tito&n.11 out=tito&n.11(keep=cnxid &m._t);
by cnxid &m._t;
run;

proc sort data=tito&n.12 out=tito&n.12(keep=cnxid &m._t);
by cnxid &m._t;
run;

Data tito&n.2;
set xy74;
if (&m._t > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m._t);
by cnxid descending &m._t;
run;

Data tito&n;
set tito&n.2 tito&n.12 tito&n.11;
by cnxid;

if (first.cnxid) then do;
   &m=.;
end;

if (&m._t > 999992) then do;
   &m=&m._t;
end;
if (&m._t <= 999992) then do;
   if &m.=999997 then &m.=0;
   if &m.=999996 then &m.=0;
   if &m.=999995 then &m.=0;
   if &m.=999994 then &m.=0;
   &m.+&m._t;
end;

run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%en(56,tot_cls_unpaid_bal_rep_6);


%macro eoi(n,m);

Data tito&n.11
     tito&n.12
;
set xy71;
if (0 <= &m._t <= 999992) then output tito&n.11;
else if (&m._t < 0) then output tito&n.12;
run;

proc sort data=tito&n.11 out=tito&n.11(keep=cnxid &m._t);
by cnxid &m._t;
run;

proc sort data=tito&n.12 out=tito&n.12(keep=cnxid &m._t);
by cnxid &m._t;
run;

Data tito&n.2;
set xy71;
if (&m._t > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m._t);
by cnxid descending &m._t;
run;

Data tito&n;
set tito&n.2 tito&n.12 tito&n.11;
by cnxid;

if (first.cnxid) then do;
   &m=.;
end;

if (&m._t > 999992) then do;
   &m=&m._t;
end;
if (&m._t <= 999992) then do;
   if &m.=999997 then &m.=0;
   if &m.=999996 then &m.=0;
   if &m.=999995 then &m.=0;
   if &m.=999994 then &m.=0;
   &m+&m._t;
end;

run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;

%eoi(55,tot_open_bal);

%macro eo(n,m);

Data tito&n.11
     tito&n.12
;
set xy71;
if (0 <= &m <= 999992) then output tito&n.11;
else if (&m < 0) then output tito&n.12;
run;

proc sort data=tito&n.11 out=tito&n.11(keep=cnxid &m);
by cnxid &m;
run;

proc sort data=tito&n.12 out=tito&n.12(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy71;
if (&m > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.12 tito&n.11;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;

%eo(60,max_open_bal_3);
%eo(61,max_open_bal_6);
%eo(62,max_open_bal_12); 
%eo(63,max_bal_rep_6);
%eo(631,maxbal_1);

%macro eu(n,m);

Data tito&n.11
     tito&n.12
;
set xy71;
if (0 <= &m.t <= 999992) then output tito&n.11;
else if (&m.t < 0) then output tito&n.12;
run;

proc sort data=tito&n.11 out=tito&n.11(keep=cnxid &m.t);
by cnxid &m.t;
run;

proc sort data=tito&n.12 out=tito&n.12(keep=cnxid &m.t);
by cnxid &m.t;
run;

Data tito&n.2;
set xy71;
if (&m.t > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m.t);
by cnxid descending &m.t;
run;

Data tito&n;
set tito&n.2 tito&n.12 tito&n.11;
run; 

proc sort data=tito&n out=tito&n;
by cnxid;
run;

Data tito&n;
set tito&n;
by cnxid;

if (first.cnxid) then do;
   &m=.;
end;

if &m.t > 999992 then do;
   &m=&m.t;
end;
else if &m.t <= 999992 then do;
   if &m=999999 then &m=0;
   if &m=999997 then &m=0;
   if &m=999996 then &m=0;
   if &m=999995 then &m=0;
   &m+&m.t;
end;

keep cnxid &m;

run;

%mend;

%eu(57,avg_bal_3);
%eu(58,avg_bal_6);
%eu(59,avg_bal_12);

%macro f(n,m);

Data tito&n.1;
set xy8;
if (&m <= 999992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy8;
if (&m > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%f(64,tot_choffamt_rep_6);
%f(65,curchoffamt);

%macro g(n,m);

Data tito&n.1;
set xy9;
if (0 <= &m <= 999992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy9;
if (&m > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%g(66,age_avg_connect_1);

%macro h(n,m);

Data tito&n.1;
set xy10;
if (0 <= &m <= 999992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy10;
if (&m > 999992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%h(67,age_avg_disconnect_1);

%macro i(n,m);

Data tito&n.1;
set xy11;
if (0 <= &m <= 992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy11;
if (&m > 992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%i(68,age_avg_inv_disconnect_1);

%macro j(n,m);

Data tito&n.1;
set xy12;
if (0 <= &m <= 992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy12;
if (&m > 992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%j(69,age_avg_vol_disconnect_1);

%macro k(n,m);

Data tito&n.1;
set xy13;
if (0 <= &m <= 992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy13;
if (&m > 992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%k(70,avg_cpaybal_1);

%macro q(n,m);

Data tito&n.1;
set xy5;
if (0 <= &m <= 92);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy5;
if (&m > 92);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%q(71,wrst);
%q(72,wrst_3);
%q(73,wrst_6);
%q(74,wrst_12);

%macro r(n,m);

Data tito&n.1;
set xy6;
if (0 <= &m <= 992);
run;

proc sort data=tito&n.1 out=tito&n.1(keep=cnxid &m);
by cnxid &m;
run;

Data tito&n.2;
set xy6;
if (&m > 992);
run;

proc sort data=tito&n.2 out=tito&n.2(keep=cnxid &m);
by cnxid descending &m;
run;

Data tito&n;
set tito&n.2 tito&n.1;
run;

proc sort data=tito&n out=tito&n;
by cnxid;
run;

%mend;
%r(75,age_0);
%r(76,mos_last_P);
%r(77,mos_last_9);
%r(78,mos_last_N);
%r(79,mos_last_F);
%r(80,mos_last_U);
%r(81,mos_last_B);

proc sort data=xy71(keep=cnxid n_open_3_1 n_open_6_1 n_open_12_1) out=titom;
by cnxid;
run;

proc sort data=xy13(keep=cnxid n_cpay) out=titop;
by cnxid;
run;

/* shewjen - all to all_temp below */
proc sort data=all_temp(keep=
cnxid mos_since_reported Acct_status 
S01 S02 S03 S04 S05 S06 S07 S08 S09 S10 S11 S12 S13 S14 S15 S16 S17 S18 S19 S20 S21 S22 S23 S24 
DT01 DT02 DT03 DT04 DT05 DT06 DT07 DT08 DT09 DT10 DT11 DT12 
Curr_bal bal01 bal02 bal03 bal04 bal05 bal06 bal07) out=alln;
by cnxid;
run;

Data tito;
merge 
alln titon titom titop tito0
tito1 tito2 tito2a tito3 tito4 tito5 tito6 tito7 tito8 tito9 tito10
tito11 tito12 tito13 tito14 tito15 tito16 tito17 tito18 tito19 tito20
tito21 tito22 tito23 tito24 tito25 tito26 tito27 tito28 tito29 tito30
tito31 tito32 tito33 tito34 tito35 tito36 tito37 tito38 tito39 tito40
tito41 tito42 tito43 tito44 tito45 tito46 tito47 tito48 tito49 tito50
tito51 tito52 tito53 tito54 tito55 tito56 tito57 tito58 tito59 tito60
tito61 tito62 tito63 tito64 tito65 tito66 tito67 tito68 tito69 tito70
tito71 tito72 tito73 tito74 tito75 tito76 tito77 tito78 tito79 tito80
tito81 tito511 tito631
;
by cnxid;
run;

proc sort data=tito out=tito;
by cnxid;
run;

Data alltr;
set tito;
run;

Data all1;
set tito;
by cnxid;

if (last.cnxid) then output all1;

run;

Data all1;
set all1;

** percent open balance ****;
if (curbal=999999|tot_open_bal=999999) then perc_open_bal=999;
else if (curbal=999997|tot_open_bal=999997) then perc_open_bal=997;
else if (curbal=999996|tot_open_bal=999996) then perc_open_bal=996;
else if (curbal=999995|tot_open_bal=999995) then perc_open_bal=995;
else if (curbal=999994|tot_open_bal=999994) then perc_open_bal=994;
else if (curbal < 0.01 ) then perc_open_bal=994;
else do;
                if( tot_open_bal < 0  ) then perc_open_bal=0;
                else
                     perc_open_bal=round((tot_open_bal/curbal)*100,0.01);
               if(perc_open_bal > 992) then perc_open_bal=992;
end;

** percent cls unpaid rep balance ****;
 if (tot_cls_unpaid_bal_rep_6=999999|tot_bal_rep_6=999999) then perc_cls_unpaid_bal_rep_6=999;
 else if (tot_cls_unpaid_bal_rep_6=999997|tot_bal_rep_6=999997) then perc_cls_unpaid_bal_rep_6=997;
 else if (tot_cls_unpaid_bal_rep_6=999996|tot_bal_rep_6=999996) then perc_cls_unpaid_bal_rep_6=996;
 else if (tot_cls_unpaid_bal_rep_6=999995|tot_bal_rep_6=999995) then perc_cls_unpaid_bal_rep_6=995;
 else if 0.01 <= tot_bal_rep_6 then do;
  if tot_cls_unpaid_bal_rep_6 < 0 then perc_cls_unpaid_bal_rep_6=0;
  if (tot_cls_unpaid_bal_rep_6 >= 0 and perc_cls_unpaid_bal_rep_6 <= 992) then
           perc_cls_unpaid_bal_rep_6=round((tot_cls_unpaid_bal_rep_6/tot_bal_rep_6)*100,0.01);
 end;
 else if tot_bal_rep_6 < 0.01 then perc_cls_unpaid_bal_rep_6=994;

** percent 30 DPD to Total Trades ***;

if (num_1_wrst=99|num_accounts_rep_6=99) then perc_1_rep_6=999;
else if (num_1_wrst=97|num_accounts_rep_6=97) then perc_1_rep_6=997;
else if (num_1_wrst=95|num_accounts_rep_6=95) then perc_1_rep_6=995;
else if (num_1_wrst=.|num_accounts_rep_6=.|num_accounts_rep_6=0) then perc_1_rep_6=994;
else if (0 <= num_1_wrst <= 92) and (1 <= num_accounts_rep_6 <= 92) then do;
   perc_1_rep_6=round((num_1_wrst/num_accounts_rep_6)*100,0.01);
end;

** percent 60+ DPD or Derog Trades to Total Trades ***;

if (num_2p_unpaid_wrst=99|num_accounts_rep_6=99) then perc_2p_unpaid_rep_6=999;
else if (num_2p_unpaid_wrst=97|num_accounts_rep_6=97) then perc_2p_unpaid_rep_6=997;
else if (num_2p_unpaid_wrst=95|num_accounts_rep_6=95) then perc_2p_unpaid_rep_6=995;
else if (num_2p_unpaid_wrst=.|num_accounts_rep_6=.|num_accounts_rep_6=0) then perc_2p_unpaid_rep_6=994;
else if (0 <= num_2p_unpaid_wrst <= 92) and (1 <= num_accounts_rep_6 <= 92) then do;
   perc_2p_unpaid_rep_6=round((num_2p_unpaid_wrst/num_accounts_rep_6)*100,0.01);
end;

** percent 90+ DPD or Derog Trades to Total Trades ***;

if (num_3p_unpaid_wrst=99|num_accounts_rep_6=99) then perc_3p_unpaid_rep_6=999;
else if (num_3p_unpaid_wrst=97|num_accounts_rep_6=97) then perc_3p_unpaid_rep_6=997;
else if (num_3p_unpaid_wrst=95|num_accounts_rep_6=95) then perc_3p_unpaid_rep_6=995;
else if (num_3p_unpaid_wrst=.|num_accounts_rep_6=.|num_accounts_rep_6=0) then perc_3p_unpaid_rep_6=994;
else if (0 <= num_3p_unpaid_wrst <= 92) and (1 <= num_accounts_rep_6 <= 92) then do;
   perc_3p_unpaid_rep_6=round((num_3p_unpaid_wrst/num_accounts_rep_6)*100,0.01);
end;

*** TOT1001 - Percent of Satisfactory Accounts to Total Accounts Reported in Last 6 Months ***;
   if cnxid=' ' then perc_sat_rep_6=999;
   else if cnxid ne ' ' and (num_0_wrst=97 or num_accounts_rep_6=97) then perc_sat_rep_6=997;
   else if cnxid ne ' ' and (num_0_wrst=95 or num_accounts_rep_6=95) then perc_sat_rep_6=995;
   else if cnxid ne ' ' and (num_accounts_rep_6 =0 or num_accounts_rep_6=.) then perc_sat_rep_6=994;
   else if cnxid ne ' ' and (1 <= num_accounts_rep_6 <= 92) then do;
      if perc_sat_rep_6 <= 992 then perc_sat_rep_6=round(((num_0_wrst/num_accounts_rep_6)*100),0.01);
   end;

 run;


Data all1;
set all1;

 ** average open balances in 3,6,12 mos ***;
 if (avg_bal_3=999999) then avg_open_bal_3=999999;
 else if (avg_bal_3=999997) then avg_open_bal_3=999997;
 else if (avg_bal_3=999996) then avg_open_bal_3=999996;
 else if (avg_bal_3=999995) then avg_open_bal_3=999995;
 else if (n_open_3_1=0|n_open_3_1=.|avg_bal_3=.|avg_bal_3=999994) then avg_open_bal_3=999994;
 else if n_open_3_1 > 0 then avg_open_bal_3=(avg_bal_3/n_open_3_1);
 avg_open_bal_3=round(avg_open_bal_3*1,0.01);

 if (avg_bal_6=999999) then avg_open_bal_6=999999;
 else if (avg_bal_6=999997) then avg_open_bal_6=999997;
 else if (avg_bal_6=999996) then avg_open_bal_6=999996;
 else if (avg_bal_6=999995) then avg_open_bal_6=999995;
 else if (n_open_6_1=0|n_open_6_1=.|avg_bal_6=.|avg_bal_6=999994) then avg_open_bal_6=999994;
 else if n_open_6_1 > 0 then avg_open_bal_6=(avg_bal_6/n_open_6_1);
 avg_open_bal_6=round(avg_open_bal_6*1,0.01);

 if (avg_bal_12=999999) then avg_open_bal_12=999999;
 else if (avg_bal_12=999997) then avg_open_bal_12=999997;
 else if (avg_bal_12=999996) then avg_open_bal_12=999996;
 else if (avg_bal_12=999995) then avg_open_bal_12=999995;
 else if (n_open_12_1=0|n_open_12_1=.|avg_bal_12=.|avg_bal_12=999994) then avg_open_bal_12=999994;
 else if n_open_12_1 > 0 then avg_open_bal_12=(avg_bal_12/n_open_12_1);
 avg_open_bal_12=round(avg_open_bal_12*1,0.01);

 *** average age of connection ***;
 if age_avg_connect_1=999999 then age_avg_connect=999;
 else if age_avg_connect_1=999997 then age_avg_connect=997;
 else if age_avg_connect_1=999995 then age_avg_connect=995;
 else if (age_avg_connect_1=.|age_avg_connect_1=999999|age_avg_connect_1=999997|age_avg_connect_1=999995|n=.|n=0) then age_avg_connect=994;
 else if n > 0 then do;
    if age_avg_connect <= 992 then age_avg_connect=(age_avg_connect_1/n);
    age_avg_connect=round(age_avg_connect*1,1);
 end;

 *** average age of disconnection ***;
 if age_avg_disconnect_1=999999 then age_avg_disconnect=999;
 **else if age_avg_disconnect_1=999997 then age_avg_disconnect=997**;
 else if age_avg_disconnect_1=999995 then age_avg_disconnect=995;
 else if (age_avg_disconnect_1=.|age_avg_disconnect_1=999999|age_avg_disconnect_1=999997|age_avg_disconnect_1=999995|n_disconnect=.|n_disconnect=0) then age_avg_disconnect=994;
 else if (age_avg_disconnect_1 <= 999992 and n_disconnect > 0) then age_avg_disconnect=(age_avg_disconnect_1/n_disconnect);
 age_avg_disconnect=round(age_avg_disconnect*1,1);

 *** average age of involuntary disconnection ***;
 if age_avg_inv_disconnect_1=999 then age_avg_inv_disconnect=999;
 else if age_avg_inv_disconnect_1=997 then age_avg_inv_disconnect=997;
 else if age_avg_inv_disconnect_1=995 then age_avg_inv_disconnect=995;
 else if (age_avg_inv_disconnect_1=.|n_inv_disconnect=.|n_inv_disconnect=0) then age_avg_inv_disconnect=994;
 else if n_inv_disconnect > 0 then age_avg_inv_disconnect=(age_avg_inv_disconnect_1/n_inv_disconnect);
 age_avg_inv_disconnect=round(age_avg_inv_disconnect*1,1);

 *** average age of voluntary disconnection ***;
 if age_avg_vol_disconnect_1=999 then age_avg_vol_disconnect=999;
 else if age_avg_vol_disconnect_1=997 then age_avg_vol_disconnect=997;
 else if age_avg_vol_disconnect_1=995 then age_avg_vol_disconnect=995;
 else if (age_avg_vol_disconnect_1=.|n_vol_disconnect=.|n_vol_disconnect=0) then age_avg_vol_disconnect=994;
 else if n_vol_disconnect > 0 then age_avg_vol_disconnect=(age_avg_vol_disconnect_1/n_vol_disconnect);
 age_avg_vol_disconnect=round(age_avg_vol_disconnect*1,1);

*********************************************************************************************************************************************;
 if avg_cpaybal_1=999 then avg_cpaybal=999;
 else if avg_cpaybal_1=997 then avg_cpaybal=997;
 else if (avg_cpaybal_1=.|n_cpay=.|n_cpay=0) then avg_cpaybal=994;
 else if n_cpay > 0 then avg_cpaybal=(avg_cpaybal_1/n_cpay);
 avg_cpaybal=round(avg_cpaybal*1,0.01);

run;


Data all1;
set all1;

keep cnxid age_avg_connect_1 n n_disconnect age_avg_disconnect_1 n_inv_disconnect age_avg_inv_disconnect_1 
     n_vol_disconnect age_avg_vol_disconnect_1
tot_bal_rep_6 
tot_open_bal 
curbal 
perc_open_bal 
avg_open_bal_3 
avg_open_bal_6 
avg_open_bal_12 

perc_sat_rep_6
perc_1_rep_6
perc_2p_unpaid_rep_6
perc_3p_unpaid_rep_6

tot_cls_unpaid_bal_rep_6 
perc_cls_unpaid_bal_rep_6 

curchoffamt 
tot_choffamt_rep_6 

curpay 
num_0_3 
num_0_6 
num_0_12 
num_1_3 
num_1_6 
num_1_12 
num_2_3 
num_2_6 
num_2_12 
num_0_wrst 
num_0_wrst_3 
num_0_wrst_6 
num_0_wrst_12 
num_1_wrst 
num_1_wrst_3 
num_1_wrst_6 
num_1_wrst_12 
num_2p_wrst 
num_2p_wrst_3 
num_2p_wrst_6 
num_2p_wrst_12
num_2p_unpaid_wrst 
num_2p_unpaid_wrst_3 
num_2p_unpaid_wrst_6 
num_2p_unpaid_wrst_12 
num_3p_wrst 
num_3p_wrst_3 
num_3p_wrst_6 
num_3p_wrst_12 
num_3p_unpaid_wrst 
num_3p_unpaid_wrst_3 
num_3p_unpaid_wrst_6 
num_3p_unpaid_wrst_12 

age_avg_connect age_avg_disconnect age_avg_inv_disconnect age_avg_vol_disconnect

avg_cpaybal
;
run;


proc sort tagsort data=all1 out=all1;
by cnxid;
run;

*********** Age of oldest connection ************;
Data all_con_1;
set alltr;
if (0 <= age_connected2 <= 992);
run;

Data all_con_2;
set alltr;
if (age_connected2 > 992);
run;

proc sort data=all_con_1 out=all_con_1;
by cnxid age_connected2;
run;

proc sort data=all_con_2 out=all_con_2;
by cnxid descending age_connected2;
run;

Data all_oc_1(keep=cnxid age_oldest_connect);
set all_con_1;
by cnxid;

if (last.cnxid) then age_oldest_connect=age_connected2;
if (last.cnxid) then output all_oc_1;
run;

Data all_oc_2(keep=cnxid age_oldest_connect);
set all_con_2;
by cnxid;

if (last.cnxid) then age_oldest_connect=age_connected2;
if (last.cnxid) then output all_oc_2;
run;

Data all_oc;
set all_oc_2 all_oc_1;
run;

proc sort data=all_oc out=all_oc ;
by cnxid;
run;

Data all_oc;
set all_oc;
by cnxid;

if (last.cnxid);

run;

*********** Age of newest connection ************;
Data all_new_1;
set alltr;
if (0 <= age_connected2 <= 992);
run;

Data all_new_2;
set alltr;
if (age_connected2 > 992);
run;

proc sort data=all_new_1 out=all_new_1;
by cnxid age_connected2;
run;

proc sort data=all_new_2 out=all_new_2;
by cnxid descending age_connected2;
run;

Data all_nc_1(keep=cnxid age_newest_connect);
set all_new_1;
by cnxid;

if (first.cnxid) then age_newest_connect=age_connected2;
if (first.cnxid) then output all_nc_1;
run;

Data all_nc_2(keep=cnxid age_newest_connect);
set all_new_2;
by cnxid;

if (first.cnxid) then age_newest_connect=age_connected2;
if (first.cnxid) then output all_nc_2;
run;

Data all_new;
set all_nc_2 all_nc_1;
run;

proc sort data=all_new out=all_new ;
by cnxid;
run;

Data all_new;
set all_new;
by cnxid;

if (last.cnxid);

run;

*********** Age of newest 0 connection 6 months ************;
Data all_0_nc_1;
set alltr;
if (0 <= age_0_connected2_6 <= 992);
run;

Data all_0_nc_2;
set alltr;
if (age_0_connected2_6 > 992);
run;

proc sort data=all_0_nc_1 out=all_0_nc_1;
by cnxid age_0_connected2_6;
run;

proc sort data=all_0_nc_2 out=all_0_nc_2;
by cnxid age_0_connected2_6;
run;

Data all_0_nc_1(keep=cnxid age_newest_0_connect_6);
set all_0_nc_1;
by cnxid;

if (first.cnxid) then age_newest_0_connect_6=age_0_connected2_6;
if (first.cnxid) then output all_0_nc_1;
run;

Data all_0_nc_2(keep=cnxid age_newest_0_connect_6);
set all_0_nc_2;
by cnxid;

if (first.cnxid) then age_newest_0_connect_6=age_0_connected2_6;
if (first.cnxid) then output all_0_nc_2;
run;

Data all_0_nc;
set all_0_nc_2 all_0_nc_1;
run;

proc sort data=all_0_nc out=all_0_nc ;
by cnxid;
run;

Data all_0_nc;
set all_0_nc;
by cnxid;

if (last.cnxid);

run;

*********** Age of newest 0 connection in Last 24 Months************;
proc sort data=all_temp out=all6;   /* shewjen - all to all_temp */
by cnxid descending mos_since_connected;
run;

Data alltr2;
set all6;

If Acct_status='0' then satisfactory=0;
Else if Acct_status =' ' and S01='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11='0'  then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12='0'  then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13='0'  then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14='0'  then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and S16='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and
S16 =' ' and S17='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and
 S16 =' ' and S17 =' ' and S18='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and
 S16 =' ' and S17 =' ' and S18 =' ' and S19='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and
 S16 =' ' and S17 =' ' and S18 =' ' and S19 =' ' and S20='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and
 S16 =' ' and S17 =' ' and S18 =' ' and S19 =' ' and S20 =' ' and S21='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and
 S16 =' ' and S17 =' ' and S18 =' ' and S19 =' ' and S20 =' ' and S21 =' ' and S22='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and
 S16 =' ' and S17 =' ' and S18 =' ' and S19 =' ' and S20 =' ' and S21 =' ' and S22 =' ' and S23='0' then satisfactory=0;
Else if Acct_status =' ' and S01 =' ' and S02 =' ' and S03 =' ' and S04 =' ' and S05 =' ' and S06 =' ' and S07 =' ' and S08 =' ' and S09 =' ' and S10 =' ' and S11 =' ' and S12 =' ' and S13 =' ' and S14 =' ' and S15 =' ' and
 S16 =' ' and S17 =' ' and S18 =' ' and S19 =' ' and S20 =' ' and S21 =' ' and S22 =' ' and S23 =' ' and S24='0' then satisfactory=0;


if cnxid=' ' then age_newest_0_connect2=999;
else if cnxid ne ' ' and satisfactory ne 0 then age_newest_0_connect2=995;
else if cnxid ne ' ' and satisfactory=0 and mos_since_connected=999 then age_newest_0_connect2=995;
else if cnxid ne ' ' and satisfactory=0 and (0 <= mos_since_connected <= 992) then do;
    age_newest_0_connect2=mos_since_connected;
end;   
keep cnxid age_newest_0_connect2;
run;
  
Data all_0_oc_n1;
set alltr2;
if (0 <= age_newest_0_connect2 <= 992);
run;

Data all_0_oc_n2;
set alltr2;
if (age_newest_0_connect2 > 992);
run;

proc sort data=all_0_oc_n1 out=all_0_oc_n1;
by cnxid age_newest_0_connect2;
run;

proc sort data=all_0_oc_n2 out=all_0_oc_n2;
by cnxid age_newest_0_connect2;
run;

Data all_0_oc_n1(keep=cnxid age_newest_0_connect);
set all_0_oc_n1;
by cnxid;

if (first.cnxid) then age_newest_0_connect=age_newest_0_connect2;
 
if (first.cnxid) then output all_0_oc_n1;
run;

Data all_0_oc_n2(keep=cnxid age_newest_0_connect);
set all_0_oc_n2;
by cnxid;

if (first.cnxid) then age_newest_0_connect=age_newest_0_connect2;
if (first.cnxid) then output all_0_oc_n2;
run;

Data all_0_new_oc;
set all_0_oc_n2 all_0_oc_n1;
run;

proc sort data=all_0_new_oc out=all_0_new_oc ;
by cnxid;
run;

Data all_0_new_oc;
set all_0_new_oc;
by cnxid;

if (last.cnxid);

run;
*/
*********** Age of oldest 0 connection ************;
Data all_0_oc_1;
set alltr;
if (0 <= age_0_connected2 <= 992);
run;

Data all_0_oc_2;
set alltr;
if (age_0_connected2 > 992);
run;

proc sort data=all_0_oc_1 out=all_0_oc_1;
by cnxid age_0_connected2;
run;

proc sort data=all_0_oc_2 out=all_0_oc_2;
by cnxid age_0_connected2;
run;

Data all_0_oc_1(keep=cnxid age_oldest_0_connect);
set all_0_oc_1;
by cnxid;

if (last.cnxid) then age_oldest_0_connect=age_0_connected2;
if (last.cnxid) then output all_0_oc_1;
run;

Data all_0_oc_2(keep=cnxid age_oldest_0_connect);
set all_0_oc_2;
by cnxid;

if (last.cnxid) then age_oldest_0_connect=age_0_connected2;
if (last.cnxid) then output all_0_oc_2;
run;

Data all_0_old_oc;
set all_0_oc_2 all_0_oc_1;
run;

proc sort data=all_0_old_oc out=all_0_old_oc ;
by cnxid;
run;

Data all_0_old_oc;
set all_0_old_oc;
by cnxid;

if (last.cnxid);

run;

*********** Age of newest disconnection ************;
Data all_ndc_1;
set alltr;
if (0 <= age_disconnected2 <= 992);
run;

Data all_ndc_2;
set alltr;
if (age_disconnected2 > 992);
run;

proc sort data=all_ndc_1(keep=cnxid age_disconnected2) out=all_ndc_1;
by cnxid;
run;

proc sort data=all_ndc_2(keep=cnxid age_disconnected2) out=all_ndc_2;
by cnxid;
run;

Data all_ndc_1;
set all_ndc_1;
by cnxid;

if (first.cnxid) then age_newest_disconnect=age_disconnected2;
if (first.cnxid) then output all_ndc_1;
run;

Data all_ndc_2;
set all_ndc_2;
by cnxid;

if (first.cnxid) then age_newest_disconnect=age_disconnected2;
if (first.cnxid) then output all_ndc_2;
run;

Data all_ndc;
set all_ndc_2 all_ndc_1;
run;

proc sort data=all_ndc out=all_ndc ;
by cnxid;
run;

Data all_ndc;
set all_ndc;
by cnxid;

if (last.cnxid);

keep cnxid age_newest_disconnect;

run;

*********** Age of newest voluntary/involuntary disconnection ************;
%macro idcon(vol);

Data all_n&vol.dc_1(keep=cnxid age_&vol._disconnected2);
set alltr;
if (0 <= age_&vol._disconnected2 <= 992);
run;

Data all_n&vol.dc_2(keep=cnxid age_&vol._disconnected2);
set alltr;
if (age_&vol._disconnected2 > 992);
run;

proc sort data=all_n&vol.dc_1 out=all_n&vol.dc_1;
by cnxid;
run;

proc sort data=all_n&vol.dc_2 out=all_n&vol.dc_2;
by cnxid;
run;

Data all_n&vol.dc_1(keep=cnxid age_newest_&vol._disconnect);
set all_n&vol.dc_1;
by cnxid;
if (first.cnxid) then age_newest_&vol._disconnect=age_&vol._disconnected2;
if (first.cnxid) then output all_n&vol.dc_1;
run;

Data all_n&vol.dc_2(keep=cnxid age_newest_&vol._disconnect);
set all_n&vol.dc_2;
by cnxid;
if (first.cnxid) then age_newest_&vol._disconnect=age_&vol._disconnected2;
if (first.cnxid) then output all_n&vol.dc_2;
run;

Data all_n&vol.dc;
set all_n&vol.dc_2 all_n&vol.dc_1;
run;

proc sort data=all_n&vol.dc out=all_n&vol.dc ;
by cnxid;
run;

Data all_n&vol.dc;
set all_n&vol.dc;
by cnxid;

if (last.cnxid);

run;

%mend;

%idcon(inv);
%idcon(vol);



********** Worst current rating *******;
Data all_w_1;
set alltr;
if (0 <= wrst <= 92);
run;

Data all_w_2;
set alltr;
if (wrst > 92);
run;

proc sort data=all_w_1(keep=cnxid wrst) out=all_w_1;
by cnxid wrst;
run;

proc sort data=all_w_2(keep=cnxid wrst) out=all_w_2;
by cnxid wrst;
run;

Data all_w_1(keep=cnxid wrst);
set all_w_1;
by cnxid ;
if (last.cnxid);
run;

Data all_w_2(keep=cnxid wrst);
set all_w_2;
by cnxid ;
if (last.cnxid);
run;

Data all_w;
set all_w_2 all_w_1;
run;

proc sort data=all_w ;
by cnxid ;
run;

Data all_w;
set all_w;

by cnxid;

if (last.cnxid);

run;

********** Worst ratings 3 6 12 months *******;
%macro wrst(nummos);

Data all_w&nummos._1;
set alltr;
if (0 <= wrst_&nummos <= 92);
run;

Data all_w&nummos._2;
set alltr;
if (wrst_&nummos > 92);
run;

proc sort data=all_w&nummos._1(keep=cnxid wrst_&nummos) out=all_w&nummos._1;
by cnxid wrst_&nummos;
run;

proc sort data=all_w&nummos._2(keep=cnxid wrst_&nummos) out=all_w&nummos._2;
by cnxid wrst_&nummos;
run;

Data all_w&nummos._1(keep=cnxid wrst_&nummos);
set all_w&nummos._1;
by cnxid ;
if (last.cnxid);
run;

Data all_w&nummos._2(keep=cnxid wrst_&nummos);
set all_w&nummos._2;
by cnxid ;
if (last.cnxid);
run;

Data all_w&nummos.;
set all_w&nummos._2 all_w&nummos._1;
run;

proc sort data=all_w&nummos ;
by cnxid ;
run;

Data all_w&nummos;
set all_w&nummos;
by cnxid;

if (last.cnxid);

run;

%mend;

%wrst(3);
%wrst(6);
%wrst(12);

*** Months since most recent Unpaid Closed(U),Fraud(F),Paid Closed(9),Non Pay Disconnect(N),Never Pay Disconnect(P),BKP(B) ***;

%macro fr(rate);

    data mos_last_&rate._1;
    set alltr;
    if mos_last_&rate <= 992 ;
    run;

    proc sort data=mos_last_&rate._1;
    by cnxid mos_last_&rate;
    run;

    Data mos_last_&rate._1;
    set mos_last_&rate._1;
    by cnxid;
    if (first.cnxid);
    run;

    data mos_last_&rate._2;
    set alltr;
    if mos_last_&rate > 992 ;
    run;

    proc sort data=mos_last_&rate._2;
    by cnxid mos_last_&rate;
    run;

    Data mos_last_&rate._2;
    set mos_last_&rate._2;
    by cnxid;
    if (first.cnxid);
    run;

    Data mos_last_&rate;
    set mos_last_&rate._1 mos_last_&rate._2;
    run;

    proc sort data=mos_last_&rate(keep=cnxid mos_last_&rate);
    by cnxid;
    run;

    Data mos_last_&rate;
    set mos_last_&rate;
    by cnxid;
    if (first.cnxid);
    run;

%mend;

*** mos_last9,mos_lastF,mos_lastU,mos_lastP,mos_lastN,mos_lastB ***;
%fr(9);
%fr(F);
%fr(U);
%fr(P);
%fr(N);
%fr(B);



*********** Months since last status/delinq/unpaid closed ************;
%macro mon(rate);

Data mos_&rate._1;
set alltr;
if (0 <= age_&rate <= 992);
run;

Data mos_&rate._2;
set alltr;
if (age_&rate > 992);
run;

proc sort data=mos_&rate._1(keep=cnxid age_&rate) out=mos_&rate._1;
by cnxid;
run;

proc sort data=mos_&rate._2(keep=cnxid age_&rate) out=mos_&rate._2;
by cnxid;
run;

Data mos_&rate._1;
set mos_&rate._1;
by cnxid;

if (first.cnxid) then mos_last_&rate = age_&rate;
if (first.cnxid) then output mos_&rate._1;

run;

Data mos_&rate._2;
set mos_&rate._2;
by cnxid;

if (first.cnxid) then mos_last_&rate = age_&rate;
if (first.cnxid) then output mos_&rate._2;

run;

Data mos_&rate;
set mos_&rate._2 mos_&rate._1;
run;

proc sort data=mos_&rate out=mos_&rate ;
by cnxid;
run;

Data mos_&rate;
set mos_&rate;
by cnxid;

if (last.cnxid);

keep cnxid mos_last_&rate;

run;

%mend;

%mon(0);
%mon(1p);
%mon(1p_unpaid);
%mon(2p);
%mon(2p_unpaid);
%mon(3p);
%mon(3p_unpaid);
%mon(unpaid);

***** months since most recent charge off ***********;
Data all_choff(keep=cnxid Reportg_dt Srv_Typ Curr_Bal_dt run_dt Charge_off_amt CHG01 DT01 CHG02 DT02 CHG03 DT03 CHG04 DT04 CHG05 DT05 CHG06 DT06
               CHG07 DT07 CHG08 DT08 CHG09 DT09 CHG10 CHG11 CHG12 CHG13 CHG14 CHG15 CHG16 CHG17 CHG18 CHG19 CHG20 CHG21 CHG22 CHG23 CHG24
               age_choff DT10 DT11
            DT12 DT13 DT14 DT15 DT16 DT17 DT18 DT19 DT20 DT21 DT22 DT23 DT24
);
set all_temp;   /* shewjen - all to all_temp */

array choff{24} CHG01 CHG02 CHG03 CHG04 CHG05 CHG06 CHG07 CHG08 CHG09
               CHG10 CHG11 CHG12 CHG13 CHG14 CHG15 CHG16 CHG17 CHG18
               CHG19 CHG20 CHG21 CHG22 CHG23 CHG24
;
do i=1 to 24;
   if choff{i} < 0 then choff{i}=0;
end;
if Charge_off_amt < 0 then Charge_off_amt=0;

if cnxid=' ' then age_choff=999;
else if cnxid ne ' ' and
     (Curr_Bal_dt=. & DT01=. & DT02=. & DT03=. & DT04=. & DT05=. & DT06=. & DT07=. & DT08=. & DT09=. &
      DT10=. & DT11=. & DT12=. & DT13=. & DT14=. & DT15=. & DT16=. & DT17=. & DT18=. & DT19=. & DT20=. &
      DT21=. & DT22=. & DT23=. & DT24=.) then age_choff=995;
else if cnxid ne ' ' and (Charge_off_amt=0 & CHG01=0 & CHG02=0 & CHG03=0 & CHG04=0 & CHG05=0 & CHG06=0 & CHG07=0 &
                          CHG08=0 & CHG09=0 & CHG10=0 & CHG11=0 & CHG12=0 & CHG13=0 & CHG14=0 & CHG15=0 & CHG16=0 &
                          CHG17=0 & CHG18=0 & CHG19=0 & CHG20=0 & CHG21=0 & CHG22=0 & CHG23=0 & CHG24=0) then age_choff=995;


else if cnxid ne ' ' then do;

***** Code changed back to use 24 months history - assumption for implementation feed *****;
if (Charge_off_amt > 0 & CHG01 <= 0) then age_choff=intck('month',Curr_Bal_dt,run_dt);
else if (CHG01 > 0 & CHG02 <= 0) then age_choff=intck('month',DT01,run_dt);
else if (CHG02 > 0 & CHG03 <= 0) then age_choff=intck('month',DT02,run_dt);
else if (CHG03 > 0 & CHG04 <= 0) then age_choff=intck('month',DT03,run_dt);
else if (CHG04 > 0 & CHG05 <= 0) then age_choff=intck('month',DT04,run_dt);
else if (CHG05 > 0 & CHG06 <= 0) then age_choff=intck('month',DT05,run_dt);
else if (CHG06 > 0 & CHG07 <= 0) then age_choff=intck('month',DT06,run_dt);
else if (CHG07 > 0 & CHG08 <= 0) then age_choff=intck('month',DT07,run_dt);
else if (CHG08 > 0 & CHG09 <= 0) then age_choff=intck('month',DT08,run_dt);
else if (CHG09 > 0 & CHG10 <= 0) then age_choff=intck('month',DT09,run_dt);
else if (CHG10 > 0 & CHG11 <= 0) then age_choff=intck('month',DT10,run_dt);
else if (CHG11 > 0 & CHG12 <= 0) then age_choff=intck('month',DT11,run_dt);
else if (CHG12 > 0 & CHG13 <= 0) then age_choff=intck('month',DT12,run_dt);
else if (CHG13 > 0 & CHG14 <= 0) then age_choff=intck('month',DT13,run_dt);
else if (CHG14 > 0 & CHG15 <= 0) then age_choff=intck('month',DT14,run_dt);
else if (CHG15 > 0 & CHG16 <= 0) then age_choff=intck('month',DT15,run_dt);
else if (CHG16 > 0 & CHG17 <= 0) then age_choff=intck('month',DT16,run_dt);
else if (CHG17 > 0 & CHG18 <= 0) then age_choff=intck('month',DT17,run_dt);
else if (CHG18 > 0 & CHG19 <= 0) then age_choff=intck('month',DT18,run_dt);
else if (CHG19 > 0 & CHG20 <= 0) then age_choff=intck('month',DT19,run_dt);
else if (CHG20 > 0 & CHG21 <= 0) then age_choff=intck('month',DT20,run_dt);
else if (CHG21 > 0 & CHG22 <= 0) then age_choff=intck('month',DT21,run_dt);
else if (CHG22 > 0 & CHG23 <= 0) then age_choff=intck('month',DT22,run_dt);
else if (CHG23 > 0 & CHG24 <= 0) then age_choff=intck('month',DT23,run_dt);
else if (CHG24 > 0 ) then age_choff=intck('month',DT24,run_dt);

if age_choff > 24 then age_choff=995;

end;

run;

Data choff_1;
set all_choff;
if (0 <= age_choff <= 992);
run;

Data choff_2;
set all_choff;
if (age_choff > 992);
run;

proc sort data=choff_1 out=choff_1;
by cnxid age_choff;
run;

proc sort data=choff_2 out=choff_2;
by cnxid age_choff;
run;

Data choff_1(keep=cnxid age_choff age_newest_choff);
set choff_1(keep=cnxid age_choff);
by cnxid;
if (first.cnxid) then age_newest_choff=age_choff;
if (first.cnxid);
run;

Data choff_2(keep=cnxid age_choff age_newest_choff);
set choff_2(keep=cnxid age_choff);
by cnxid;
if (first.cnxid) then age_newest_choff=age_choff;
if (first.cnxid);
run;

Data mos_choff;
set choff_2 choff_1;
run;

proc sort data=mos_choff out=mos_choff ;
by cnxid;
run;

Data mos_choff;
set mos_choff;
by cnxid;

if (last.cnxid);

keep cnxid age_newest_choff;

run;

*************** Maximum Open Balance 3,6,12 months ******************;
%macro mbal(mos);

Data mxobal_&mos._1;
set alltr;
if (max_open_bal_&mos <= 999992);
run;

Data mxobal_&mos._2;
set alltr;
if (max_open_bal_&mos > 999992);
run;

proc sort data=mxobal_&mos._1(keep=cnxid max_open_bal_&mos) out= mxobal_&mos._1;
by cnxid;
run;

proc sort data=mxobal_&mos._2(keep=cnxid max_open_bal_&mos) out= mxobal_&mos._2;
by cnxid;
run;

Data mxobal_&mos._1;
set mxobal_&mos._1;
by cnxid;
if (last.cnxid);
run;

Data mxobal_&mos._2;
set mxobal_&mos._2;
by cnxid;
if (last.cnxid);
run;

Data mxobal_&mos;
set mxobal_&mos._2 mxobal_&mos._1;
run;

proc sort data=mxobal_&mos out=mxobal_&mos ;
by cnxid;
run;

Data mxobal_&mos ;
set mxobal_&mos ;
by cnxid;

if (last.cnxid);

run;

%mend;
%mbal(3);
%mbal(6);
%mbal(12);

*************** Maximum of Current Balances Reported in Last 6 Months ******************;
Data mxcbal_rep6_1;
set alltr;
if (max_bal_rep_6 <= 999992);
run;

Data mxcbal_rep6_2;
set alltr;
if (max_bal_rep_6 > 999992);
run;

proc sort data=mxcbal_rep6_1(keep=cnxid max_bal_rep_6) out=mxcbal_rep6_1;
by cnxid;
run;

proc sort data=mxcbal_rep6_2(keep=cnxid max_bal_rep_6) out=mxcbal_rep6_2;
by cnxid;
run;

Data mxcbal_rep6_1;
set mxcbal_rep6_1;
by cnxid;
if (last.cnxid);
run;

Data mxcbal_rep6_2;
set mxcbal_rep6_2;
by cnxid;
if (last.cnxid);
run;

Data mxcbal_rep6;
set mxcbal_rep6_2 mxcbal_rep6_1;
run;

proc sort data=mxcbal_rep6 out=mxcbal_rep6 ;
by cnxid;
run;

Data mxcbal_rep6;
set mxcbal_rep6;
by cnxid;

if (last.cnxid);

run;

*************** Maximum Current - New coding******************;
Data mxcbal_1;
set alltr;
if (maxbal_1 <= 999992);
run;

Data mxcbal_2;
set alltr;
if (maxbal_1 > 999992);
run;

proc sort data=mxcbal_1(keep=cnxid maxbal_1) out=mxcbal_1;
by cnxid;
run;

proc sort data=mxcbal_2(keep=cnxid maxbal_1) out=mxcbal_2;
by cnxid;
run;

Data mxcbal_1;
set mxcbal_1;
by cnxid;
if (last.cnxid);
run;

Data mxcbal_2;
set mxcbal_2;
by cnxid;
if (last.cnxid);
run;

Data mxcbal;
set mxcbal_2 mxcbal_1;
run;

proc sort data=mxcbal out=mxcbal ;
by cnxid;
run;

Data mxcbal;
set mxcbal;
by cnxid;

if (last.cnxid);

run;

********************************************************************************************************************;

Data all_var1(/* drop=
tot_bal_rep_6
tot_open_bal
curbal
tot_cls_unpaid_bal_rep_6
curchoffamt
tot_choffamt_rep_6
curpay
num_0_3
num_0_6
num_0_12
num_1_3
num_1_6
num_1_12
num_2_3
num_2_6
num_2_12
num_0_wrst
num_0_wrst_3
num_0_wrst_6
num_0_wrst_12
num_1_wrst
num_1_wrst_3
num_1_wrst_6
num_1_wrst_12
num_2p_wrst
num_2p_wrst_3
num_2p_wrst_6
num_2p_wrst_12
num_2p_unpaid_wrst
num_2p_unpaid_wrst_3
num_2p_unpaid_wrst_6
num_2p_unpaid_wrst_12
num_3p_wrst
num_3p_wrst_3
num_3p_wrst_6
num_3p_wrst_12
num_3p_unpaid_wrst
num_3p_unpaid_wrst_3
num_3p_unpaid_wrst_6
num_3p_unpaid_wrst_12
n n_disconnect n_inv_disconnect n_vol_disconnect mos_since_connected
wrst wrst_3 wrst_6 wrst_12 */)
;
merge   
           all_oc 
           all_new 
           all_ndc 
           all_ninvdc 
           all_nvoldc 
           all_0_nc 
           all_0_old_oc 
           all_0_new_oc 
           all_w 
           all_w3 all_w6 all_w12 
           mos_last_9 mos_last_U mos_last_N mos_last_F mos_last_B mos_last_P 
           mos_0 mos_1p mos_1p_unpaid mos_2p mos_2p_unpaid mos_3p mos_3p_unpaid mos_unpaid 
           mos_choff mxobal_3 mxobal_6 mxobal_12 mxcbal_rep6 mxcbal 
;
by cnxid;
run;

proc sort data=all_var1 out=all_var1;
by cnxid;
run;

/* Data all_var1;
merge all_var1
      all_w
      all_w3 all_w6 all_w12
      mos_last_9 
;
by cnxid;
run;

proc sort data=all_var1 out=all_var1;
by cnxid;
run; */


proc sort data=all1 out=all1;
by cnxid;
run;

Data all_var2;
merge all1 all_var1;
by cnxid;
if age_newest_inv_disconnect>=995 then age_newest_inv_disconnect_24=age_newest_inv_disconnect;
else if age_newest_inv_disconnect>24 then age_newest_inv_disconnect_24=995;
else  age_newest_inv_disconnect_24=age_newest_inv_disconnect;
run;




%macro keeplist;

TOT1001
TOT1003
TOT1004
TOT1005
TOT0116
TOT0117
TOT0118
TOT0119
TOT0120
TOT0121
TOT0122
TOT0123
TOT0124
TOT0125
TOT0126
TOT0127
TOT0128
TOT0129
TOT0130
TOT0131
TOT0132
TOT0133
TOT0134
TOT0135
TOT0136
TOT0137
TOT0138
TOT0139
TOT0201
TOT0202
TOT0203
TOT0204
TOT0205
TOT0206
TOT0207
TOT0208
TOT0209
TOT0210
TOT0211
TOT0212
TOT0213
TOT0214
TOT0215
TOT0216
TOT0217
TOT0301
TOT0302
TOT0303
TOT0304
TOT0401
TOT0402
TOT0403
TOT0404
TOT0501
TOT0601
TOT0602
TOT0603
TOT0701
TOT0702
TOT0703
TOT0704
TOT0801
TOT0901
TOT0902
TOT0903
TOT0904
TOT0905
TOT0906
TOT0907
TOT0908
TOT0909
TOT1101
TOT1201
TOT1202
TOT2101
TOT2102
TOT2103
TOT2105
age_newest_inv_disconnect_24

%mend;

 ** List of Vars in Keeplist are a subset of the entire Keystone Attribute List due to the obs point of the analysis 11/09 NC+ extract **;
 ** Utility data and length of history in the DB for aggregation are the limitations **;
 

Data ncvar2_def(keep=cnxid %keeplist);
set all_var2;

** Round Bal to 2 decimal place **;
If tot_bal_rep_6 <= 999992 then tot_bal_rep_6=put(tot_bal_rep_6,8.2);
else tot_bal_rep_6=put(tot_bal_rep_6,8.);

If tot_open_bal <= 999992 then tot_open_bal=put(tot_open_bal,8.2);
else tot_open_bal=put(tot_open_bal,8.);


If curbal <= 999992 then curbal=put(curbal,8.2);
else curbal=put(curbal,8.);

If perc_open_bal <= 992 then perc_open_bal=put(perc_open_bal,8.2);
else perc_open_bal=put(perc_open_bal,8.);

If perc_sat_rep_6 <= 992 then perc_sat_rep_6=put(perc_sat_rep_6,8.2);
else perc_sat_rep_6=put(perc_sat_rep_6,8.);

If perc_cls_paid_rep_6 <= 992 then perc_cls_paid_rep_6=put(perc_cls_paid_rep_6,8.2);
else perc_cls_paid_rep_6=put(perc_cls_paid_rep_6,8.);

If perc_1_rep_6 <= 992 then perc_1_rep_6=put(perc_1_rep_6,8.2);
else perc_1_rep_6=put(perc_1_rep_6,8.);

If perc_2p_unpaid_rep_6 <= 992 then perc_2p_unpaid_rep_6=put(perc_2p_unpaid_rep_6,8.2);
else perc_2p_unpaid_rep_6=put(perc_2p_unpaid_rep_6,8.);

If perc_3p_unpaid_rep_6 <= 992 then perc_3p_unpaid_rep_6=put(perc_3p_unpaid_rep_6,8.2);
else perc_3p_unpaid_rep_6=put(perc_3p_unpaid_rep_6,8.);

If perc_cls_unpaid_rep_6 <= 992 then perc_cls_unpaid_rep_6=put(perc_cls_unpaid_rep_6,8.2);
else perc_cls_unpaid_rep_6=put(perc_cls_unpaid_rep_6,8.);

If perc_open2 <= 992 then perc_open2=put(perc_open2,8.2);
else perc_open2=put(perc_open2,8.);

If avg_open_bal_3 <= 999992 then avg_open_bal_3=put(avg_open_bal_3,8.2);
else avg_open_bal_3=put(avg_open_bal_3,8.);


If avg_open_bal_6 <= 999992 then avg_open_bal_6=put(avg_open_bal_6,8.2);
else avg_open_bal_6=put(avg_open_bal_6,8.);


If avg_open_bal_12 <= 999992 then avg_open_bal_12=put(avg_open_bal_12,8.2);
else avg_open_bal_12=put(avg_open_bal_12,8.);


If curpay <= 999992 then curpay=put(curpay,8.2);
else curpay=put(curpay,8.);

If curchoffamt <= 999992 then curchoffamt=put(curchoffamt,8.2);
else curchoffamt=put(curchoffamt,8.);

If tot_choffamt_rep_6 <= 999992 then tot_choffamt_rep_6=put(tot_choffamt_rep_6,8.2);
else tot_choffamt_rep_6=put(tot_choffamt_rep_6,8.);


If tot_cls_unpaid_bal_rep_6 <= 999992 then tot_cls_unpaid_bal_rep_6 =put(tot_cls_unpaid_bal_rep_6,8.2);
else tot_cls_unpaid_bal_rep_6=put(tot_cls_unpaid_bal_rep_6,8.);


*/
 **** Attribute Capping ****;
 /* if age_oldest_connect > 992 then age_oldest_connect = 992;
 if age_oldest_0_connect > 992 then age_oldest_0_connect = 992;
 if tot_bal_rep_6 > 999992 then tot_bal_rep_6 = 999992;
 if tot_open_bal > 999992 then tot_open_bal = 999992;
 if curbal > 999992 then curbal = 999992;
 if perc_open_bal > 992 then perc_open_bal = 992;
 if avg_open_bal_3 > 999992 then avg_open_bal_3 = 999992;
 if avg_open_bal_6 > 999992 then avg_open_bal_6 = 999992;
 if avg_open_bal_12 > 999992 then avg_open_bal_12 = 999992;
 if max_open_bal_3 > 999992 then max_open_bal_3 = 999992;
 if max_open_bal_6 > 999992 then max_open_bal_6 = 999992;
 if max_open_bal_12 > 999992 then max_open_bal_12 = 999992;
 if max_bal_rep_6 > 999992 then max_bal_rep_6 = 999992;
 if tot_cls_unpaid_bal_rep_6 > 999992 then tot_cls_unpaid_bal_rep_6 = 999992;
 if perc_cls_unpaid_bal_rep_6 > 992 then perc_cls_unpaid_bal_rep_6 = 992;
 if age_newest_connect > 992 then age_newest_connect = 992;
 if age_newest_0_connect > 992 then age_newest_0_connect = 992;
 if age_newest_disconnect > 992 then age_newest_disconnect = 992;
 if age_newest_inv_disconnect > 992 then age_newest_inv_disconnect = 992;
 if age_newest_vol_disconnect > 992 then age_newest_vol_disconnect = 992;
 if curpay > 999992 then curpay = 999992;
 if num_0_3 > 92 then num_0_3 = 92;
 if num_0_6 > 92 then num_0_6 = 92;
 if num_0_12 > 92 then num_0_12 = 92;
 if num_1_3 > 92 then num_1_3 = 92;
 if num_1_6 > 92 then num_1_6 = 92;
 if num_1_12 > 92 then num_1_12 = 92;
 if num_2_3 > 92 then num_2_3 = 92;
 if num_2_6 > 92 then num_2_6 = 92;
 if num_2_12 > 92 then num_2_12 = 92;
 if  num_0_wrst > 92 then  num_0_wrst = 92;
 if  num_0_wrst_3 > 92 then  num_0_wrst_3 = 92;
 if  num_0_wrst_6 > 92 then  num_0_wrst_6 = 92;
 if  num_0_wrst_12 > 92 then  num_0_wrst_12 = 92;
 if  num_1_wrst > 92 then  num_1_wrst = 92;
 if  num_1_wrst_3 > 92 then  num_1_wrst_3 = 92;
 if  num_1_wrst_6 > 92 then  num_1_wrst_6 = 92;
 if  num_1_wrst_12 > 92 then  num_1_wrst_12 = 92;
 if  num_2p_wrst > 92 then  num_2p_wrst = 92;
 if  num_2p_wrst_3 > 92 then  num_2p_wrst_3 = 92;
 if  num_2p_wrst_6 > 92 then  num_2p_wrst_6 = 92;
 if  num_2p_wrst_12 > 92 then  num_2p_wrst_12 = 92;
 if  num_2p_unpaid_wrst > 92 then  num_2p_unpaid_wrst = 92;
 if  num_2p_unpaid_wrst_3 > 92 then  num_2p_unpaid_wrst_3 = 92;
 if  num_2p_unpaid_wrst_6 > 92 then  num_2p_unpaid_wrst_6 = 92;
 if  num_2p_unpaid_wrst_12 > 92 then  num_2p_unpaid_wrst_12 = 92;
 if  num_3p_wrst > 92 then  num_3p_wrst = 92;
 if  num_3p_wrst_3 > 92 then  num_3p_wrst_3 = 92;
 if  num_3p_wrst_6 > 92 then  num_3p_wrst_6 = 92;
 if  num_3p_wrst_12 > 92 then  num_3p_wrst_12 = 92;
 if  num_3p_unpaid_wrst > 92 then  num_3p_unpaid_wrst = 92;
 if  num_3p_unpaid_wrst_3 > 92 then  num_3p_unpaid_wrst_3 = 92;
 if  num_3p_unpaid_wrst_6 > 92 then  num_3p_unpaid_wrst_6 = 92;
 if  num_3p_unpaid_wrst_12 > 92 then  num_3p_unpaid_wrst_12 = 92;
 if mos_last_0 > 992 then mos_last_0 = 992;
 if mos_last_F > 992 then mos_last_F = 992;
 if mos_last_1p > 992 then mos_last_1p = 992;
 if mos_last_1p_unpaid > 992 then mos_last_1p_unpaid = 992;
 if mos_last_2p > 992 then mos_last_2p = 992;
 if mos_last_2p_unpaid > 992 then mos_last_2p_unpaid = 992;
 if mos_last_3p > 992 then mos_last_3p = 992;
 if mos_last_3p_unpaid > 992 then mos_last_3p_unpaid = 992;
 if mos_last_unpaid > 992 then mos_last_unpaid = 992;
 if mos_last_9 > 992 then mos_last_9 = 992;
 if age_newest_choff > 992 then age_newest_choff = 992;
 if curchoffamt > 999992 then curchoffamt = 999992;
 if tot_choffamt_rep_6 > 999992 then tot_choffamt_rep_6 = 999992;
 if age_avg_connect > 992 then age_avg_connect = 992;
 if age_avg_disconnect > 992 then age_avg_disconnect = 992;
 if age_avg_inv_disconnect > 992 then age_avg_inv_disconnect = 992;
 if age_avg_vol_disconnect > 992 then age_avg_vol_disconnect = 992;
 if avg_cpaybal > 992 then avg_cpaybal = 992; */

 *** RENAME AND LABEL - KEYSTONE ATTRIBUTES ***;
*** Rename variable names to final Keystone Attribute variable names ***;
RENAME
perc_sat_rep_6 = TOT1001
perc_1_rep_6 = TOT1003
perc_2p_unpaid_rep_6 = TOT1004
perc_3p_unpaid_rep_6 = TOT1005
age_oldest_connect = TOT0201
age_oldest_0_connect = TOT0202 
wrst = TOT0301
wrst_3 = TOT0302
wrst_6 = TOT0303
wrst_12 = TOT0304
tot_bal_rep_6 = TOT0401
tot_open_bal = TOT0402
curbal = TOT0403
perc_open_bal = TOT0501
avg_open_bal_3 = TOT0601
avg_open_bal_6 = TOT0602
avg_open_bal_12 = TOT0603
max_open_bal_3 = TOT0701
max_open_bal_6 = TOT0702
max_open_bal_12 = TOT0703
max_bal_rep_6 = TOT0704
tot_cls_unpaid_bal_rep_6 = TOT0404
perc_cls_unpaid_bal_rep_6 = TOT0502
age_newest_connect = TOT0203
age_newest_0_connect_6 = TOT0204
age_newest_disconnect = TOT0205
age_newest_inv_disconnect = TOT0206
age_newest_vol_disconnect = TOT0207
curpay = TOT0801
num_0_3 = TOT0901
num_0_6 = TOT0902
num_0_12 = TOT0903
num_1_3 = TOT0904
num_1_6 = TOT0905
num_1_12 = TOT0906
num_2_3 = TOT0907
num_2_6 = TOT0908
num_2_12 = TOT0909
 num_0_wrst = TOT0116
 num_0_wrst_3 = TOT0117
 num_0_wrst_6 = TOT0118
 num_0_wrst_12 = TOT0119
 num_1_wrst = TOT0120
 num_1_wrst_3 = TOT0121
 num_1_wrst_6 = TOT0122
 num_1_wrst_12 = TOT0123
 num_2p_wrst = TOT0124
 num_2p_wrst_3 = TOT0125
 num_2p_wrst_6 = TOT0126
 num_2p_wrst_12 = TOT0127
 num_2p_unpaid_wrst = TOT0128
 num_2p_unpaid_wrst_3 = TOT0129
 num_2p_unpaid_wrst_6 = TOT0130
 num_2p_unpaid_wrst_12 = TOT0131
 num_3p_wrst = TOT0132
 num_3p_wrst_3 = TOT0133
 num_3p_wrst_6 = TOT0134
 num_3p_wrst_12 = TOT0135
 num_3p_unpaid_wrst = TOT0136
 num_3p_unpaid_wrst_3 = TOT0137
 num_3p_unpaid_wrst_6 = TOT0138
 num_3p_unpaid_wrst_12 = TOT0139
mos_last_0 = TOT0208
mos_last_F = TOT0209
mos_last_1p = TOT0210
mos_last_1p_unpaid = TOT0211
mos_last_2p = TOT0212
mos_last_2p_unpaid = TOT0213
mos_last_3p = TOT0214
mos_last_3p_unpaid = TOT0215
mos_last_unpaid = TOT0216
mos_last_9 = TOT0217
age_newest_choff = TOT1101
curchoffamt = TOT1201
tot_choffamt_rep_6 = TOT1202
age_avg_connect = TOT2101
age_avg_disconnect = TOT2102
age_newest_0_connect = TOT2103
maxbal_1 = TOT2105
;

/* shewjen log5
 %inc "&path./ncvar2_name_labels_keystone.sas"; 
**********************************************************/

run;

/* shewjen log5
proc means data=ncvar2_def;
var _numeric_;
run;
**************************************/

data ncvar2_final(rename=(
TOT1001	=	XMA1311
TOT1003	=	XMA1321
TOT1004	=	XMA1326
TOT1005	=	XMA1331
TOT0116	=	XMA1396
TOT0117	=	XMA1221
TOT0118	=	XMA1226
TOT0119	=	XMA1231
TOT0120	=	XMA1397
TOT0121	=	XMA1236
TOT0122	=	XMA1241
TOT0123	=	XMA1246
TOT0124	=	XMA1398
TOT0125	=	XMA1251
TOT0126	=	XMA1256
TOT0127	=	XMA1261
TOT0128	=	XMA1399
TOT0129	=	XMA1266
TOT0130	=	XMA1271
TOT0131	=	XMA1276
TOT0132	=	XMA1400
TOT0133	=	XMA1401
TOT0134	=	XMA1402
TOT0135	=	XMA1403
TOT0136	=	XMA1404
TOT0137	=	XMA1405
TOT0138	=	XMA1406
TOT0139	=	XMA1407
TOT0201	=	XMA1001
TOT0202	=	XMA1394
TOT0203	=	XMA1151
TOT0204	=	XMA1414
TOT0205	=	XMA1156
TOT0206	=	XMA1162
TOT0207	=	XMA1166
TOT0208	=	XMA1341
TOT0209	=	XMA1346
TOT0210	=	XMA1351
TOT0211	=	XMA1408
TOT0212	=	XMA1356
TOT0213	=	XMA1409
TOT0214	=	XMA1361
TOT0215	=	XMA1410
TOT0216	=	XMA1411
TOT0217	=	XMA1412
TOT0301	=	XMA1016
TOT0302	=	XMA1021
TOT0303	=	XMA1026
TOT0304	=	XMA1031
TOT0401	=	XMA1036
TOT0402	=	XMA1041
TOT0403	=	XMA1046
TOT0404	=	XMA1091
TOT0501	=	XMA1051
TOT0601	=	XMA1056
TOT0602	=	XMA1061
TOT0603	=	XMA1066
TOT0701	=	XMA1071
TOT0702	=	XMA1076
TOT0703	=	XMA1081
TOT0704	=	XMA1395
TOT0801	=	XMA1171
TOT0901	=	XMA1176
TOT0902	=	XMA1181
TOT0903	=	XMA1186
TOT0904	=	XMA1191
TOT0905	=	XMA1196
TOT0906	=	XMA1201
TOT0907	=	XMA1206
TOT0908	=	XMA1211
TOT0909	=	XMA1216
TOT1101	=	XMA1366
TOT1201	=	XMA1371
TOT1202	=	XMA1376
TOT2101	=	XMA1413
TOT2102	=	XMA1416
TOT2103	=	XMA1415
TOT2105	=	XMA1086
age_newest_inv_disconnect_24= XMA1161
));
set ncvar2_def;
label	TOT1001=	'Percent of Satisfactory Trades to Total Trades Reported in Last 6 Months';
label	TOT1003=	'Percent of 30 DPD Trades  to Total Trades Reported in Last 6 Months';
label	TOT1004=	'Percent of 60+ DPD or Derogatory Trades to Total Trades Reported in Last 6 Months';
label	TOT1005=	'Percent of 90+ DPD or Derogatory Trades to Total Trades Reported in Last 6 Months';
label	TOT0116=	'Number of Satisfactory Trades Reported in Last 6 Months';
label	TOT0117=	'Number of Worst Ever Satisfactory Trades Reported In the Last 3 Months';
label	TOT0118=	'Number of Worst Ever Satisfactory Trades Reported In Last 6 Months';
label	TOT0119=	'Number of Worst Ever Satisfactory Trades Reported In Last 12 Months';
label	TOT0120=	'Number of Trades 30 DPD Reported in Last 6 Months';
label	TOT0121=	'Number of Worst Ever 30 DPD Trades Reported In Last 3 Months';
label	TOT0122=	'Number of Worst Ever 30 DPD Trades Reported In Last 6 Months';
label	TOT0123=	'Number of Worst Ever 30 DPD Trades Reported In Last 12 Months';
label	TOT0124=	'Number of Trades 60+ DPD Reported in Last 6 Months';
label	TOT0125=	'Number of Worst Ever 60+ DPD Trades Reported In Last 3 Months';
label	TOT0126=	'Number of Worst Ever 60+ DPD Trades Reported In Last 6 Months';
label	TOT0127=	'Number of Worst Ever 60+ DPD Trades Reported In Last 12 Months';
label	TOT0128=	'Number of Trades 60+ DPD or Derogatory Reported in Last 6 Months';
label	TOT0129=	'Number of Worst Ever 60+ DPD or Derogatory Trades Reported In Last 3 Months';
label	TOT0130=	'Number of Worst Ever 60+ DPD or Derogatory Trades Reported In Last 6 Months';
label	TOT0131=	'Number of Worst Ever 60+ DPD or Derogatory Trades Reported In Last 12 Months';
label	TOT0132=	'Number of Trades 90+ DPD Reported in Last 6 Months';
label	TOT0133=	'Number of Worst Ever 90+ DPD Trades Reported in Last 3 Months';
label	TOT0134=	'Number of Worst Ever 90+ DPD Trades Reported in Last 6 Months';
label	TOT0135=	'Number of Worst Ever 90+ DPD Trades Reported in Last 12 Months';
label	TOT0136=	'Number of Trades 90+ DPD or Derogatory Reported in Last 6 Months';
label	TOT0137=	'Number of Worst Ever 90+ DPD or Derogatory Trades Reported in Last 3 Months';
label	TOT0138=	'Number of Worst Ever 90+ DPD or Derogatory Trades Reported in Last 6 Months';
label	TOT0139=	'Number of Worst Ever 90+ DPD or Derogatory Trades Reported in Last 12 Months';
label	TOT0201=	'Number of Months Since Oldest Connection';
label	TOT0202=	'Number of Months Since the Oldest Connection Satisfactory Trades';
label	TOT0203=	'Number of Months Since the Most Recent Connection';
label	TOT0204=	'Number of Months Since the Most Recent Connection for Satisfactory Trades in the Last 6 Months';
label	TOT0205=	'Number of Months Since the Most Recent Disconnection';
label	TOT0206=	'Number of Months Since the Most Recent Involuntary Disconnection';
label	TOT0207=	'Number of Months Since the Most Recent Voluntary Disconnection';
label	TOT0208=	'Number of Months Since the Most Recent Satisfactory Reported In Last 24 Months';
label	TOT0209=	'Number of Months Since the Most Recent Fraud Reported In Last 24 Months';
label	TOT0210=	'Number of Months Since the Most Recent 30+ DPD Reported In Last 24 Months';
label	TOT0211=	'Number of Months Since the Most Recent 30+ DPD or Derogatory Reported In Last 24 Months';
label	TOT0212=	'Number of Months Since the Most Recent 60+ DPD Reported In Last 24 Months';
label	TOT0213=	'Number of Months Since the Most Recent 60+ DPD or Derogatory Reported In Last 24 Months';
label	TOT0214=	'Number of Months Since the Most Recent 90+ DPD Reported In Last 24 Months';
label	TOT0215=	'Number of Months Since the Most Recent 90+ DPD or Derogatory Reported In Last 24 Months';
label	TOT0216=	'Number of Months Since the Most Recent Derogatory Reported In Last 24 Months';
label	TOT0217=	'Number of Months Since the Most Recent Paid-Closed Reported In Last 24 Months';
label	TOT0301=	'Worst Current Status Reported in Last 6 Months';
label	TOT0302=	'Worst Ever Status Reported In the Last 3 Months';
label	TOT0303=	'Worst Ever Status Reported In Last 6 Months';
label	TOT0304=	'Worst Ever Status Reported In Last 12 Months';
label	TOT0401=	'Sum of Current Balances Reported In Last 6 Months';
label	TOT0402=	'Sum of the Current Balances on Open Trades Reported in Last 2 Months';
label	TOT0403=	'Sum of the Current Balances Reported in Last 2 Months';
label	TOT0404=	'Sum of Current Balances Reported In Last 6 Months on Derogatory Accounts';
label	TOT0501=	'Percent of Current Balances of Open Trades to Current Balances of All Trades';
label	TOT0601=	'Average of Trade Level Average Open Balances In Last 3 Months on Non-Derogatory Trades';
label	TOT0602=	'Average of Trade Level Average Open Balances In Last 6 Months on Non-Derogatory Trades';
label	TOT0603=	'Average of Trade Level Average Open Balances In Last 12 Months on Non-Derogatory Trades';
label	TOT0701=	'Maximum of Open Balances In Last 3 Month on Non-Derogatory Trades';
label	TOT0702=	'Maximum of Open Balances In Last 6 Months on Non-Derogatory Trades';
label	TOT0703=	'Maximum of Open Balances In Last 12 Months on Non-Derogatory Trades';
label	TOT0704=	'Maximum Balances Reported In Last 6 Months';
label	TOT0801=	'Sum of the Current Payments Made Reported In Last 2 Months';
label	TOT0901=	'Number of Satisfactory Occurrences Reported In Last 3 Months';
label	TOT0902=	'Number of Satisfactory Occurrences Reported In Last 6 Months';
label	TOT0903=	'Number of Satisfactory Occurrences Reported In Last 12 Months';
label	TOT0904=	'Number of 30 DPD Occurrences Reported In Last 3 Months';
label	TOT0905=	'Number of 30 DPD Occurrences Reported In Last 6 Months';
label	TOT0906=	'Number of 30 DPD Occurrences Reported In Last 12 Months';
label	TOT0907=	'Number of 60 DPD Occurrences Reported In Last 3 Months';
label	TOT0908=	'Number of 60 DPD Occurrences Reported In Last 6 Months';
label	TOT0909=	'Number of 60 DPD Occurrences Reported In Last 12 Months';
label	TOT1101=	'Number of Months Since the Most Recent Charge-off Reported In Last 24 Months';
label	TOT1201=	'Sum of Current Charge-off Amounts Reported in Last 2 Months';
label	TOT1202=	'Sum of Charge-off Amounts Reported In Last 6 Months';
label	TOT2101=	'Average Number Months Since Connection';
label	TOT2102=	'Average Number Months Since Disconnection';
label	TOT2103=	'Number of Months Since the Most Recent Connection for Satisfactory Trades in the Last 24 Months';
label	TOT2105=	'Maximum Current Balance';
label   age_newest_inv_disconnect_24=  'Number of Months Since the Most Recent Involuntary Disconnection in Last 24 Months';

run;

proc contents data=ncvar2_final ;run;

 proc means data=ncvar2_final n nmiss min p1 p5 p10 p25 p50 p75 p90 p95 p99 max mean;
 var _numeric_;
 run;


