--drop table dfa_dna_ws5056_us_prd_sandbox.wg_extract_kid_split;

create or replace table dfa_dna_ws5056_us_prd_sandbox.wg_pmt_grid_logic_step_1 as

select * except(csmr_strt_dt, csmr_end_dt), extract(date from timestamp_millis(cast(csmr_strt_dt as int64))) as csmr_strt_dt, extract(date from timestamp_millis(cast(csmr_end_dt as int64))) as csmr_end_dt

from dfa_dna_ws5056_us_prd_sandbox.wg_extract_KID_split;

create or replace table dfa_dna_ws5056_us_prd_sandbox.wg_pmt_grid_modified_202201 as 
select
CNX_Key
,Surrogate_Key
,Exch
,Zip_four
,Company_cd
,Srv_Typ
,Account_number
,State_cd
,Zip
,Acct_Typ
,Acct_status
,Last_Acct_status
,case when dt01 < csmr_strt_dt then NULL when dt01 >= csmr_end_dt then NULL else S01 end as S01
,case when dt02 < csmr_strt_dt then NULL when dt02 >= csmr_end_dt then NULL else S02 end as S02
,case when dt03 < csmr_strt_dt then NULL when dt03 >= csmr_end_dt then NULL else S03 end as S03
,case when dt04 < csmr_strt_dt then NULL when dt04 >= csmr_end_dt then NULL else S04 end as S04
,case when dt05 < csmr_strt_dt then NULL when dt05 >= csmr_end_dt then NULL else S05 end as S05
,case when dt06 < csmr_strt_dt then NULL when dt06 >= csmr_end_dt then NULL else S06 end as S06
,case when dt07 < csmr_strt_dt then NULL when dt07 >= csmr_end_dt then NULL else S07 end as S07
,case when dt08 < csmr_strt_dt then NULL when dt08 >= csmr_end_dt then NULL else S08 end as S08
,case when dt09 < csmr_strt_dt then NULL when dt09 >= csmr_end_dt then NULL else S09 end as S09
,case when dt10 < csmr_strt_dt then NULL when dt10 >= csmr_end_dt then NULL else S10 end as S10
,case when dt11 < csmr_strt_dt then NULL when dt11 >= csmr_end_dt then NULL else S11 end as S11
,case when dt12 < csmr_strt_dt then NULL when dt12 >= csmr_end_dt then NULL else S12 end as S12
,case when dt13 < csmr_strt_dt then NULL when dt13 >= csmr_end_dt then NULL else S13 end as S13
,case when dt14 < csmr_strt_dt then NULL when dt14 >= csmr_end_dt then NULL else S14 end as S14
,case when dt15 < csmr_strt_dt then NULL when dt15 >= csmr_end_dt then NULL else S15 end as S15
,case when dt16 < csmr_strt_dt then NULL when dt16 >= csmr_end_dt then NULL else S16 end as S16
,case when dt17 < csmr_strt_dt then NULL when dt17 >= csmr_end_dt then NULL else S17 end as S17
,case when dt18 < csmr_strt_dt then NULL when dt18 >= csmr_end_dt then NULL else S18 end as S18
,case when dt19 < csmr_strt_dt then NULL when dt19 >= csmr_end_dt then NULL else S19 end as S19
,case when dt20 < csmr_strt_dt then NULL when dt20 >= csmr_end_dt then NULL else S20 end as S20
,case when dt21 < csmr_strt_dt then NULL when dt21 >= csmr_end_dt then NULL else S21 end as S21
,case when dt22 < csmr_strt_dt then NULL when dt22 >= csmr_end_dt then NULL else S22 end as S22
,case when dt23 < csmr_strt_dt then NULL when dt23 >= csmr_end_dt then NULL else S23 end as S23
,case when dt24 < csmr_strt_dt then NULL when dt24 >= csmr_end_dt then NULL else S24 end as S24
,Reportg_dt
,Connect_dt
,Disconnect_dt
,Charge_off_amt
,Curr_Bal_dt
,Pmt_Amt
,Curr_bal
,Last_Reporting_date
,Expiration_dt
,csmr_strt_dt
,csmr_end_dt

,case when dt01 < csmr_strt_dt then NULL when dt01 >= csmr_end_dt then NULL else dt01 end as dt01,case when dt01 < csmr_strt_dt then NULL when dt01 >= csmr_end_dt then NULL else PMT01 end as PMT01,case when dt01 < csmr_strt_dt then NULL when dt01 >= csmr_end_dt then NULL else BAL01 end as BAL01,case when dt01 < csmr_strt_dt then NULL when dt01 >= csmr_end_dt then NULL else CHG01 end as CHG01,case when dt01 < csmr_strt_dt then NULL when dt01 >= csmr_end_dt then NULL else HIST_CONNECT_DT01 end as HIST_CONNECT_DT01,case when dt01 < csmr_strt_dt then NULL when dt01 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT01 end as HIST_DISCONNECT_DT01
,case when dt02 < csmr_strt_dt then NULL when dt02 >= csmr_end_dt then NULL else dt02 end as dt02,case when dt02 < csmr_strt_dt then NULL when dt02 >= csmr_end_dt then NULL else PMT02 end as PMT02,case when dt02 < csmr_strt_dt then NULL when dt02 >= csmr_end_dt then NULL else BAL02 end as BAL02,case when dt02 < csmr_strt_dt then NULL when dt02 >= csmr_end_dt then NULL else CHG02 end as CHG02,case when dt02 < csmr_strt_dt then NULL when dt02 >= csmr_end_dt then NULL else HIST_CONNECT_DT02 end as HIST_CONNECT_DT02,case when dt02 < csmr_strt_dt then NULL when dt02 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT02 end as HIST_DISCONNECT_DT02
,case when dt03 < csmr_strt_dt then NULL when dt03 >= csmr_end_dt then NULL else dt03 end as dt03,case when dt03 < csmr_strt_dt then NULL when dt03 >= csmr_end_dt then NULL else PMT03 end as PMT03,case when dt03 < csmr_strt_dt then NULL when dt03 >= csmr_end_dt then NULL else BAL03 end as BAL03,case when dt03 < csmr_strt_dt then NULL when dt03 >= csmr_end_dt then NULL else CHG03 end as CHG03,case when dt03 < csmr_strt_dt then NULL when dt03 >= csmr_end_dt then NULL else HIST_CONNECT_DT03 end as HIST_CONNECT_DT03,case when dt03 < csmr_strt_dt then NULL when dt03 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT03 end as HIST_DISCONNECT_DT03
,case when dt04 < csmr_strt_dt then NULL when dt04 >= csmr_end_dt then NULL else dt04 end as dt04,case when dt04 < csmr_strt_dt then NULL when dt04 >= csmr_end_dt then NULL else PMT04 end as PMT04,case when dt04 < csmr_strt_dt then NULL when dt04 >= csmr_end_dt then NULL else BAL04 end as BAL04,case when dt04 < csmr_strt_dt then NULL when dt04 >= csmr_end_dt then NULL else CHG04 end as CHG04,case when dt04 < csmr_strt_dt then NULL when dt04 >= csmr_end_dt then NULL else HIST_CONNECT_DT04 end as HIST_CONNECT_DT04,case when dt04 < csmr_strt_dt then NULL when dt04 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT04 end as HIST_DISCONNECT_DT04
,case when dt05 < csmr_strt_dt then NULL when dt05 >= csmr_end_dt then NULL else dt05 end as dt05,case when dt05 < csmr_strt_dt then NULL when dt05 >= csmr_end_dt then NULL else PMT05 end as PMT05,case when dt05 < csmr_strt_dt then NULL when dt05 >= csmr_end_dt then NULL else BAL05 end as BAL05,case when dt05 < csmr_strt_dt then NULL when dt05 >= csmr_end_dt then NULL else CHG05 end as CHG05,case when dt05 < csmr_strt_dt then NULL when dt05 >= csmr_end_dt then NULL else HIST_CONNECT_DT05 end as HIST_CONNECT_DT05,case when dt05 < csmr_strt_dt then NULL when dt05 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT05 end as HIST_DISCONNECT_DT05
,case when dt06 < csmr_strt_dt then NULL when dt06 >= csmr_end_dt then NULL else dt06 end as dt06,case when dt06 < csmr_strt_dt then NULL when dt06 >= csmr_end_dt then NULL else PMT06 end as PMT06,case when dt06 < csmr_strt_dt then NULL when dt06 >= csmr_end_dt then NULL else BAL06 end as BAL06,case when dt06 < csmr_strt_dt then NULL when dt06 >= csmr_end_dt then NULL else CHG06 end as CHG06,case when dt06 < csmr_strt_dt then NULL when dt06 >= csmr_end_dt then NULL else HIST_CONNECT_DT06 end as HIST_CONNECT_DT06,case when dt06 < csmr_strt_dt then NULL when dt06 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT06 end as HIST_DISCONNECT_DT06
,case when dt07 < csmr_strt_dt then NULL when dt07 >= csmr_end_dt then NULL else dt07 end as dt07,case when dt07 < csmr_strt_dt then NULL when dt07 >= csmr_end_dt then NULL else PMT07 end as PMT07,case when dt07 < csmr_strt_dt then NULL when dt07 >= csmr_end_dt then NULL else BAL07 end as BAL07,case when dt07 < csmr_strt_dt then NULL when dt07 >= csmr_end_dt then NULL else CHG07 end as CHG07,case when dt07 < csmr_strt_dt then NULL when dt07 >= csmr_end_dt then NULL else HIST_CONNECT_DT07 end as HIST_CONNECT_DT07,case when dt07 < csmr_strt_dt then NULL when dt07 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT07 end as HIST_DISCONNECT_DT07
,case when dt08 < csmr_strt_dt then NULL when dt08 >= csmr_end_dt then NULL else dt08 end as dt08,case when dt08 < csmr_strt_dt then NULL when dt08 >= csmr_end_dt then NULL else PMT08 end as PMT08,case when dt08 < csmr_strt_dt then NULL when dt08 >= csmr_end_dt then NULL else BAL08 end as BAL08,case when dt08 < csmr_strt_dt then NULL when dt08 >= csmr_end_dt then NULL else CHG08 end as CHG08,case when dt08 < csmr_strt_dt then NULL when dt08 >= csmr_end_dt then NULL else HIST_CONNECT_DT08 end as HIST_CONNECT_DT08,case when dt08 < csmr_strt_dt then NULL when dt08 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT08 end as HIST_DISCONNECT_DT08
,case when dt09 < csmr_strt_dt then NULL when dt09 >= csmr_end_dt then NULL else dt09 end as dt09,case when dt09 < csmr_strt_dt then NULL when dt09 >= csmr_end_dt then NULL else PMT09 end as PMT09,case when dt09 < csmr_strt_dt then NULL when dt09 >= csmr_end_dt then NULL else BAL09 end as BAL09,case when dt09 < csmr_strt_dt then NULL when dt09 >= csmr_end_dt then NULL else CHG09 end as CHG09,case when dt09 < csmr_strt_dt then NULL when dt09 >= csmr_end_dt then NULL else HIST_CONNECT_DT09 end as HIST_CONNECT_DT09,case when dt09 < csmr_strt_dt then NULL when dt09 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT09 end as HIST_DISCONNECT_DT09
,case when dt10 < csmr_strt_dt then NULL when dt10 >= csmr_end_dt then NULL else dt10 end as dt10,case when dt10 < csmr_strt_dt then NULL when dt10 >= csmr_end_dt then NULL else PMT10 end as PMT10,case when dt10 < csmr_strt_dt then NULL when dt10 >= csmr_end_dt then NULL else BAL10 end as BAL10,case when dt10 < csmr_strt_dt then NULL when dt10 >= csmr_end_dt then NULL else CHG10 end as CHG10,case when dt10 < csmr_strt_dt then NULL when dt10 >= csmr_end_dt then NULL else HIST_CONNECT_DT10 end as HIST_CONNECT_DT10,case when dt10 < csmr_strt_dt then NULL when dt10 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT10 end as HIST_DISCONNECT_DT10
,case when dt11 < csmr_strt_dt then NULL when dt11 >= csmr_end_dt then NULL else dt11 end as dt11,case when dt11 < csmr_strt_dt then NULL when dt11 >= csmr_end_dt then NULL else PMT11 end as PMT11,case when dt11 < csmr_strt_dt then NULL when dt11 >= csmr_end_dt then NULL else BAL11 end as BAL11,case when dt11 < csmr_strt_dt then NULL when dt11 >= csmr_end_dt then NULL else CHG11 end as CHG11,case when dt11 < csmr_strt_dt then NULL when dt11 >= csmr_end_dt then NULL else HIST_CONNECT_DT11 end as HIST_CONNECT_DT11,case when dt11 < csmr_strt_dt then NULL when dt11 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT11 end as HIST_DISCONNECT_DT11
,case when dt12 < csmr_strt_dt then NULL when dt12 >= csmr_end_dt then NULL else dt12 end as dt12,case when dt12 < csmr_strt_dt then NULL when dt12 >= csmr_end_dt then NULL else PMT12 end as PMT12,case when dt12 < csmr_strt_dt then NULL when dt12 >= csmr_end_dt then NULL else BAL12 end as BAL12,case when dt12 < csmr_strt_dt then NULL when dt12 >= csmr_end_dt then NULL else CHG12 end as CHG12,case when dt12 < csmr_strt_dt then NULL when dt12 >= csmr_end_dt then NULL else HIST_CONNECT_DT12 end as HIST_CONNECT_DT12,case when dt12 < csmr_strt_dt then NULL when dt12 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT12 end as HIST_DISCONNECT_DT12
,case when dt13 < csmr_strt_dt then NULL when dt13 >= csmr_end_dt then NULL else dt13 end as dt13,case when dt13 < csmr_strt_dt then NULL when dt13 >= csmr_end_dt then NULL else PMT13 end as PMT13,case when dt13 < csmr_strt_dt then NULL when dt13 >= csmr_end_dt then NULL else BAL13 end as BAL13,case when dt13 < csmr_strt_dt then NULL when dt13 >= csmr_end_dt then NULL else CHG13 end as CHG13,case when dt13 < csmr_strt_dt then NULL when dt13 >= csmr_end_dt then NULL else HIST_CONNECT_DT13 end as HIST_CONNECT_DT13,case when dt13 < csmr_strt_dt then NULL when dt13 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT13 end as HIST_DISCONNECT_DT13
,case when dt14 < csmr_strt_dt then NULL when dt14 >= csmr_end_dt then NULL else dt14 end as dt14,case when dt14 < csmr_strt_dt then NULL when dt14 >= csmr_end_dt then NULL else PMT14 end as PMT14,case when dt14 < csmr_strt_dt then NULL when dt14 >= csmr_end_dt then NULL else BAL14 end as BAL14,case when dt14 < csmr_strt_dt then NULL when dt14 >= csmr_end_dt then NULL else CHG14 end as CHG14,case when dt14 < csmr_strt_dt then NULL when dt14 >= csmr_end_dt then NULL else HIST_CONNECT_DT14 end as HIST_CONNECT_DT14,case when dt14 < csmr_strt_dt then NULL when dt14 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT14 end as HIST_DISCONNECT_DT14
,case when dt15 < csmr_strt_dt then NULL when dt15 >= csmr_end_dt then NULL else dt15 end as dt15,case when dt15 < csmr_strt_dt then NULL when dt15 >= csmr_end_dt then NULL else PMT15 end as PMT15,case when dt15 < csmr_strt_dt then NULL when dt15 >= csmr_end_dt then NULL else BAL15 end as BAL15,case when dt15 < csmr_strt_dt then NULL when dt15 >= csmr_end_dt then NULL else CHG15 end as CHG15,case when dt15 < csmr_strt_dt then NULL when dt15 >= csmr_end_dt then NULL else HIST_CONNECT_DT15 end as HIST_CONNECT_DT15,case when dt15 < csmr_strt_dt then NULL when dt15 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT15 end as HIST_DISCONNECT_DT15
,case when dt16 < csmr_strt_dt then NULL when dt16 >= csmr_end_dt then NULL else dt16 end as dt16,case when dt16 < csmr_strt_dt then NULL when dt16 >= csmr_end_dt then NULL else PMT16 end as PMT16,case when dt16 < csmr_strt_dt then NULL when dt16 >= csmr_end_dt then NULL else BAL16 end as BAL16,case when dt16 < csmr_strt_dt then NULL when dt16 >= csmr_end_dt then NULL else CHG16 end as CHG16,case when dt16 < csmr_strt_dt then NULL when dt16 >= csmr_end_dt then NULL else HIST_CONNECT_DT16 end as HIST_CONNECT_DT16,case when dt16 < csmr_strt_dt then NULL when dt16 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT16 end as HIST_DISCONNECT_DT16
,case when dt17 < csmr_strt_dt then NULL when dt17 >= csmr_end_dt then NULL else dt17 end as dt17,case when dt17 < csmr_strt_dt then NULL when dt17 >= csmr_end_dt then NULL else PMT17 end as PMT17,case when dt17 < csmr_strt_dt then NULL when dt17 >= csmr_end_dt then NULL else BAL17 end as BAL17,case when dt17 < csmr_strt_dt then NULL when dt17 >= csmr_end_dt then NULL else CHG17 end as CHG17,case when dt17 < csmr_strt_dt then NULL when dt17 >= csmr_end_dt then NULL else HIST_CONNECT_DT17 end as HIST_CONNECT_DT17,case when dt17 < csmr_strt_dt then NULL when dt17 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT17 end as HIST_DISCONNECT_DT17
,case when dt18 < csmr_strt_dt then NULL when dt18 >= csmr_end_dt then NULL else dt18 end as dt18,case when dt18 < csmr_strt_dt then NULL when dt18 >= csmr_end_dt then NULL else PMT18 end as PMT18,case when dt18 < csmr_strt_dt then NULL when dt18 >= csmr_end_dt then NULL else BAL18 end as BAL18,case when dt18 < csmr_strt_dt then NULL when dt18 >= csmr_end_dt then NULL else CHG18 end as CHG18,case when dt18 < csmr_strt_dt then NULL when dt18 >= csmr_end_dt then NULL else HIST_CONNECT_DT18 end as HIST_CONNECT_DT18,case when dt18 < csmr_strt_dt then NULL when dt18 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT18 end as HIST_DISCONNECT_DT18
,case when dt19 < csmr_strt_dt then NULL when dt19 >= csmr_end_dt then NULL else dt19 end as dt19,case when dt19 < csmr_strt_dt then NULL when dt19 >= csmr_end_dt then NULL else PMT19 end as PMT19,case when dt19 < csmr_strt_dt then NULL when dt19 >= csmr_end_dt then NULL else BAL19 end as BAL19,case when dt19 < csmr_strt_dt then NULL when dt19 >= csmr_end_dt then NULL else CHG19 end as CHG19,case when dt19 < csmr_strt_dt then NULL when dt19 >= csmr_end_dt then NULL else HIST_CONNECT_DT19 end as HIST_CONNECT_DT19,case when dt19 < csmr_strt_dt then NULL when dt19 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT19 end as HIST_DISCONNECT_DT19
,case when dt20 < csmr_strt_dt then NULL when dt20 >= csmr_end_dt then NULL else dt20 end as dt20,case when dt20 < csmr_strt_dt then NULL when dt20 >= csmr_end_dt then NULL else PMT20 end as PMT20,case when dt20 < csmr_strt_dt then NULL when dt20 >= csmr_end_dt then NULL else BAL20 end as BAL20,case when dt20 < csmr_strt_dt then NULL when dt20 >= csmr_end_dt then NULL else CHG20 end as CHG20,case when dt20 < csmr_strt_dt then NULL when dt20 >= csmr_end_dt then NULL else HIST_CONNECT_DT20 end as HIST_CONNECT_DT20,case when dt20 < csmr_strt_dt then NULL when dt20 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT20 end as HIST_DISCONNECT_DT20
,case when dt21 < csmr_strt_dt then NULL when dt21 >= csmr_end_dt then NULL else dt21 end as dt21,case when dt21 < csmr_strt_dt then NULL when dt21 >= csmr_end_dt then NULL else PMT21 end as PMT21,case when dt21 < csmr_strt_dt then NULL when dt21 >= csmr_end_dt then NULL else BAL21 end as BAL21,case when dt21 < csmr_strt_dt then NULL when dt21 >= csmr_end_dt then NULL else CHG21 end as CHG21,case when dt21 < csmr_strt_dt then NULL when dt21 >= csmr_end_dt then NULL else HIST_CONNECT_DT21 end as HIST_CONNECT_DT21,case when dt21 < csmr_strt_dt then NULL when dt21 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT21 end as HIST_DISCONNECT_DT21
,case when dt22 < csmr_strt_dt then NULL when dt22 >= csmr_end_dt then NULL else dt22 end as dt22,case when dt22 < csmr_strt_dt then NULL when dt22 >= csmr_end_dt then NULL else PMT22 end as PMT22,case when dt22 < csmr_strt_dt then NULL when dt22 >= csmr_end_dt then NULL else BAL22 end as BAL22,case when dt22 < csmr_strt_dt then NULL when dt22 >= csmr_end_dt then NULL else CHG22 end as CHG22,case when dt22 < csmr_strt_dt then NULL when dt22 >= csmr_end_dt then NULL else HIST_CONNECT_DT22 end as HIST_CONNECT_DT22,case when dt22 < csmr_strt_dt then NULL when dt22 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT22 end as HIST_DISCONNECT_DT22
,case when dt23 < csmr_strt_dt then NULL when dt23 >= csmr_end_dt then NULL else dt23 end as dt23,case when dt23 < csmr_strt_dt then NULL when dt23 >= csmr_end_dt then NULL else PMT23 end as PMT23,case when dt23 < csmr_strt_dt then NULL when dt23 >= csmr_end_dt then NULL else BAL23 end as BAL23,case when dt23 < csmr_strt_dt then NULL when dt23 >= csmr_end_dt then NULL else CHG23 end as CHG23,case when dt23 < csmr_strt_dt then NULL when dt23 >= csmr_end_dt then NULL else HIST_CONNECT_DT23 end as HIST_CONNECT_DT23,case when dt23 < csmr_strt_dt then NULL when dt23 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT23 end as HIST_DISCONNECT_DT23
,case when dt24 < csmr_strt_dt then NULL when dt24 >= csmr_end_dt then NULL else dt24 end as dt24,case when dt24 < csmr_strt_dt then NULL when dt24 >= csmr_end_dt then NULL else PMT24 end as PMT24,case when dt24 < csmr_strt_dt then NULL when dt24 >= csmr_end_dt then NULL else BAL24 end as BAL24,case when dt24 < csmr_strt_dt then NULL when dt24 >= csmr_end_dt then NULL else CHG24 end as CHG24,case when dt24 < csmr_strt_dt then NULL when dt24 >= csmr_end_dt then NULL else HIST_CONNECT_DT24 end as HIST_CONNECT_DT24,case when dt24 < csmr_strt_dt then NULL when dt24 >= csmr_end_dt then NULL else HIST_DISCONNECT_DT24 end as HIST_DISCONNECT_DT24

from dfa_dna_ws5056_us_prd_sandbox.wg_pmt_grid_logic_step_1

